// Generated by the gRPC protobuf plugin.
// If you make any local change, they will be lost.
// source: hybridsim.proto

#include "hybridsim.pb.h"
#include "hybridsim.grpc.pb.h"

#include <grpc++/channel.h>
#include <grpc++/impl/client_unary_call.h>
#include <grpc++/impl/rpc_service_method.h>
#include <grpc++/impl/service_type.h>
#include <grpc++/support/async_unary_call.h>
#include <grpc++/support/async_stream.h>
#include <grpc++/support/sync_stream.h>
namespace hybridsim {

static const char* HybridSimulation_method_names[] = {
  "/hybridsim.HybridSimulation/simulatedTimeInerval",
};

std::unique_ptr< HybridSimulation::Stub> HybridSimulation::NewStub(const std::shared_ptr< ::grpc::Channel>& channel, const ::grpc::StubOptions& options) {
  std::unique_ptr< HybridSimulation::Stub> stub(new HybridSimulation::Stub(channel));
  return stub;
}

HybridSimulation::Stub::Stub(const std::shared_ptr< ::grpc::Channel>& channel)
  : channel_(channel), rpcmethod_simulatedTimeInerval_(HybridSimulation_method_names[0], ::grpc::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status HybridSimulation::Stub::simulatedTimeInerval(::grpc::ClientContext* context, const ::hybridsim::LeftClosedRightOpenTimeInterval& request, ::hybridsim::Empty* response) {
  return ::grpc::BlockingUnaryCall(channel_.get(), rpcmethod_simulatedTimeInerval_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::hybridsim::Empty>* HybridSimulation::Stub::AsyncsimulatedTimeInervalRaw(::grpc::ClientContext* context, const ::hybridsim::LeftClosedRightOpenTimeInterval& request, ::grpc::CompletionQueue* cq) {
  return new ::grpc::ClientAsyncResponseReader< ::hybridsim::Empty>(channel_.get(), cq, rpcmethod_simulatedTimeInerval_, context, request);
}

HybridSimulation::AsyncService::AsyncService() : ::grpc::AsynchronousService(HybridSimulation_method_names, 1) {}

HybridSimulation::Service::Service() {
}

HybridSimulation::Service::~Service() {
}

::grpc::Status HybridSimulation::Service::simulatedTimeInerval(::grpc::ServerContext* context, const ::hybridsim::LeftClosedRightOpenTimeInterval* request, ::hybridsim::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

void HybridSimulation::AsyncService::RequestsimulatedTimeInerval(::grpc::ServerContext* context, ::hybridsim::LeftClosedRightOpenTimeInterval* request, ::grpc::ServerAsyncResponseWriter< ::hybridsim::Empty>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
  AsynchronousService::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
}

::grpc::RpcService* HybridSimulation::Service::service() {
  if (service_) {
    return service_.get();
  }
  service_ = std::unique_ptr< ::grpc::RpcService>(new ::grpc::RpcService());
  service_->AddMethod(new ::grpc::RpcServiceMethod(
      HybridSimulation_method_names[0],
      ::grpc::RpcMethod::NORMAL_RPC,
      new ::grpc::RpcMethodHandler< HybridSimulation::Service, ::hybridsim::LeftClosedRightOpenTimeInterval, ::hybridsim::Empty>(
          std::mem_fn(&HybridSimulation::Service::simulatedTimeInerval), this)));
  return service_.get();
}


}  // namespace hybridsim

