// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: noninteracting.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "noninteracting.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace noninteracting {

namespace {

const ::google::protobuf::Descriptor* Position_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Position_reflection_ = NULL;
const ::google::protobuf::Descriptor* Edge_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Edge_reflection_ = NULL;
const ::google::protobuf::Descriptor* SUMOTime_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SUMOTime_reflection_ = NULL;
const ::google::protobuf::Descriptor* SUMOReal_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SUMOReal_reflection_ = NULL;
const ::google::protobuf::Descriptor* MSPersonStage_Walking_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MSPersonStage_Walking_reflection_ = NULL;
const ::google::protobuf::Descriptor* CMPWlkgTm_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CMPWlkgTm_reflection_ = NULL;
const ::google::protobuf::Descriptor* GetPos_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  GetPos_reflection_ = NULL;
const ::google::protobuf::Descriptor* GetAngle_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  GetAngle_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_noninteracting_2eproto() {
  protobuf_AddDesc_noninteracting_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "noninteracting.proto");
  GOOGLE_CHECK(file != NULL);
  Position_descriptor_ = file->message_type(0);
  static const int Position_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Position, x_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Position, y_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Position, z_),
  };
  Position_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Position_descriptor_,
      Position::default_instance_,
      Position_offsets_,
      -1,
      -1,
      -1,
      sizeof(Position),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Position, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Position, _is_default_instance_));
  Edge_descriptor_ = file->message_type(1);
  static const int Edge_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Edge, fromjunctionid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Edge, tojunctionid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Edge, length_),
  };
  Edge_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Edge_descriptor_,
      Edge::default_instance_,
      Edge_offsets_,
      -1,
      -1,
      -1,
      sizeof(Edge),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Edge, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Edge, _is_default_instance_));
  SUMOTime_descriptor_ = file->message_type(2);
  static const int SUMOTime_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SUMOTime, sumotime_),
  };
  SUMOTime_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      SUMOTime_descriptor_,
      SUMOTime::default_instance_,
      SUMOTime_offsets_,
      -1,
      -1,
      -1,
      sizeof(SUMOTime),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SUMOTime, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SUMOTime, _is_default_instance_));
  SUMOReal_descriptor_ = file->message_type(3);
  static const int SUMOReal_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SUMOReal, sumoreal_),
  };
  SUMOReal_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      SUMOReal_descriptor_,
      SUMOReal::default_instance_,
      SUMOReal_offsets_,
      -1,
      -1,
      -1,
      sizeof(SUMOReal),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SUMOReal, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SUMOReal, _is_default_instance_));
  MSPersonStage_Walking_descriptor_ = file->message_type(4);
  static const int MSPersonStage_Walking_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MSPersonStage_Walking, edge_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MSPersonStage_Walking, nextrouteedge_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MSPersonStage_Walking, departpos_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MSPersonStage_Walking, arrivalpos_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MSPersonStage_Walking, maxspeed_),
  };
  MSPersonStage_Walking_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      MSPersonStage_Walking_descriptor_,
      MSPersonStage_Walking::default_instance_,
      MSPersonStage_Walking_offsets_,
      -1,
      -1,
      -1,
      sizeof(MSPersonStage_Walking),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MSPersonStage_Walking, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MSPersonStage_Walking, _is_default_instance_));
  CMPWlkgTm_descriptor_ = file->message_type(5);
  static const int CMPWlkgTm_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CMPWlkgTm, edge_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CMPWlkgTm, stage_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CMPWlkgTm, sumotime_),
  };
  CMPWlkgTm_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      CMPWlkgTm_descriptor_,
      CMPWlkgTm::default_instance_,
      CMPWlkgTm_offsets_,
      -1,
      -1,
      -1,
      sizeof(CMPWlkgTm),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CMPWlkgTm, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CMPWlkgTm, _is_default_instance_));
  GetPos_descriptor_ = file->message_type(6);
  static const int GetPos_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetPos, stage_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetPos, sumotime_),
  };
  GetPos_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      GetPos_descriptor_,
      GetPos::default_instance_,
      GetPos_offsets_,
      -1,
      -1,
      -1,
      sizeof(GetPos),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetPos, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetPos, _is_default_instance_));
  GetAngle_descriptor_ = file->message_type(7);
  static const int GetAngle_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetAngle, stage_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetAngle, sumotime_),
  };
  GetAngle_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      GetAngle_descriptor_,
      GetAngle::default_instance_,
      GetAngle_offsets_,
      -1,
      -1,
      -1,
      sizeof(GetAngle),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetAngle, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetAngle, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_noninteracting_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Position_descriptor_, &Position::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Edge_descriptor_, &Edge::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      SUMOTime_descriptor_, &SUMOTime::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      SUMOReal_descriptor_, &SUMOReal::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      MSPersonStage_Walking_descriptor_, &MSPersonStage_Walking::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      CMPWlkgTm_descriptor_, &CMPWlkgTm::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      GetPos_descriptor_, &GetPos::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      GetAngle_descriptor_, &GetAngle::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_noninteracting_2eproto() {
  delete Position::default_instance_;
  delete Position_reflection_;
  delete Edge::default_instance_;
  delete Edge_reflection_;
  delete SUMOTime::default_instance_;
  delete SUMOTime_reflection_;
  delete SUMOReal::default_instance_;
  delete SUMOReal_reflection_;
  delete MSPersonStage_Walking::default_instance_;
  delete MSPersonStage_Walking_reflection_;
  delete CMPWlkgTm::default_instance_;
  delete CMPWlkgTm_reflection_;
  delete GetPos::default_instance_;
  delete GetPos_reflection_;
  delete GetAngle::default_instance_;
  delete GetAngle_reflection_;
}

void protobuf_AddDesc_noninteracting_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\024noninteracting.proto\022\016noninteracting\"+"
    "\n\010Position\022\t\n\001x\030\001 \001(\001\022\t\n\001y\030\002 \001(\001\022\t\n\001z\030\003 "
    "\001(\001\"D\n\004Edge\022\026\n\016fromJunctionId\030\001 \001(\t\022\024\n\014t"
    "oJunctionId\030\002 \001(\t\022\016\n\006length\030\003 \001(\001\"\034\n\010SUM"
    "OTime\022\020\n\010sumoTime\030\001 \001(\001\"\034\n\010SUMOReal\022\020\n\010s"
    "umoReal\030\001 \001(\001\"\241\001\n\025MSPersonStage_Walking\022"
    "\"\n\004edge\030\001 \001(\0132\024.noninteracting.Edge\022+\n\rn"
    "extRouteEdge\030\002 \001(\0132\024.noninteracting.Edge"
    "\022\021\n\tdepartPos\030\003 \001(\001\022\022\n\narrivalPos\030\004 \001(\001\022"
    "\020\n\010maxSpeed\030\005 \001(\001\"\221\001\n\tCMPWlkgTm\022\"\n\004edge\030"
    "\001 \001(\0132\024.noninteracting.Edge\0224\n\005stage\030\002 \001"
    "(\0132%.noninteracting.MSPersonStage_Walkin"
    "g\022*\n\010sumoTime\030\003 \001(\0132\030.noninteracting.SUM"
    "OTime\"j\n\006GetPos\0224\n\005stage\030\001 \001(\0132%.noninte"
    "racting.MSPersonStage_Walking\022*\n\010sumoTim"
    "e\030\002 \001(\0132\030.noninteracting.SUMOTime\"l\n\010Get"
    "Angle\0224\n\005stage\030\001 \001(\0132%.noninteracting.MS"
    "PersonStage_Walking\022*\n\010sumoTime\030\002 \001(\0132\030."
    "noninteracting.SUMOTime2\277\003\n\006PState\022K\n\022co"
    "mputeWalkingTime\022\031.noninteracting.CMPWlk"
    "gTm\032\030.noninteracting.SUMOTime\"\000\022A\n\013getPo"
    "sition\022\026.noninteracting.GetPos\032\030.noninte"
    "racting.Position\"\000\022@\n\010getAngle\022\030.noninte"
    "racting.GetAngle\032\030.noninteracting.SUMORe"
    "al\"\000\022F\n\016getWaitingTime\022\030.noninteracting."
    "SUMOTime\032\030.noninteracting.SUMOTime\"\000\022M\n\010"
    "getSpeed\022%.noninteracting.MSPersonStage_"
    "Walking\032\030.noninteracting.SUMOReal\"\000\022L\n\013g"
    "etNextEdge\022%.noninteracting.MSPersonStag"
    "e_Walking\032\024.noninteracting.Edge\"\000B3\n\032de."
    "dlr.sumo.noninteractingB\023NonInteractingP"
    "rotoP\000b\006proto3", 1254);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "noninteracting.proto", &protobuf_RegisterTypes);
  Position::default_instance_ = new Position();
  Edge::default_instance_ = new Edge();
  SUMOTime::default_instance_ = new SUMOTime();
  SUMOReal::default_instance_ = new SUMOReal();
  MSPersonStage_Walking::default_instance_ = new MSPersonStage_Walking();
  CMPWlkgTm::default_instance_ = new CMPWlkgTm();
  GetPos::default_instance_ = new GetPos();
  GetAngle::default_instance_ = new GetAngle();
  Position::default_instance_->InitAsDefaultInstance();
  Edge::default_instance_->InitAsDefaultInstance();
  SUMOTime::default_instance_->InitAsDefaultInstance();
  SUMOReal::default_instance_->InitAsDefaultInstance();
  MSPersonStage_Walking::default_instance_->InitAsDefaultInstance();
  CMPWlkgTm::default_instance_->InitAsDefaultInstance();
  GetPos::default_instance_->InitAsDefaultInstance();
  GetAngle::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_noninteracting_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_noninteracting_2eproto {
  StaticDescriptorInitializer_noninteracting_2eproto() {
    protobuf_AddDesc_noninteracting_2eproto();
  }
} static_descriptor_initializer_noninteracting_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Position::kXFieldNumber;
const int Position::kYFieldNumber;
const int Position::kZFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Position::Position()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:noninteracting.Position)
}

void Position::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

Position::Position(const Position& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:noninteracting.Position)
}

void Position::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  x_ = 0;
  y_ = 0;
  z_ = 0;
}

Position::~Position() {
  // @@protoc_insertion_point(destructor:noninteracting.Position)
  SharedDtor();
}

void Position::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Position::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Position::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Position_descriptor_;
}

const Position& Position::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_noninteracting_2eproto();
  return *default_instance_;
}

Position* Position::default_instance_ = NULL;

Position* Position::New(::google::protobuf::Arena* arena) const {
  Position* n = new Position;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Position::Clear() {
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<Position*>(16)->f)

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(x_, z_);

#undef ZR_HELPER_
#undef ZR_

}

bool Position::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:noninteracting.Position)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional double x = 1;
      case 1: {
        if (tag == 9) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &x_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(17)) goto parse_y;
        break;
      }

      // optional double y = 2;
      case 2: {
        if (tag == 17) {
         parse_y:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &y_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(25)) goto parse_z;
        break;
      }

      // optional double z = 3;
      case 3: {
        if (tag == 25) {
         parse_z:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &z_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:noninteracting.Position)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:noninteracting.Position)
  return false;
#undef DO_
}

void Position::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:noninteracting.Position)
  // optional double x = 1;
  if (this->x() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(1, this->x(), output);
  }

  // optional double y = 2;
  if (this->y() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->y(), output);
  }

  // optional double z = 3;
  if (this->z() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->z(), output);
  }

  // @@protoc_insertion_point(serialize_end:noninteracting.Position)
}

::google::protobuf::uint8* Position::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:noninteracting.Position)
  // optional double x = 1;
  if (this->x() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(1, this->x(), target);
  }

  // optional double y = 2;
  if (this->y() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->y(), target);
  }

  // optional double z = 3;
  if (this->z() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(3, this->z(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:noninteracting.Position)
  return target;
}

int Position::ByteSize() const {
  int total_size = 0;

  // optional double x = 1;
  if (this->x() != 0) {
    total_size += 1 + 8;
  }

  // optional double y = 2;
  if (this->y() != 0) {
    total_size += 1 + 8;
  }

  // optional double z = 3;
  if (this->z() != 0) {
    total_size += 1 + 8;
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Position::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const Position* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Position>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Position::MergeFrom(const Position& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from.x() != 0) {
    set_x(from.x());
  }
  if (from.y() != 0) {
    set_y(from.y());
  }
  if (from.z() != 0) {
    set_z(from.z());
  }
}

void Position::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Position::CopyFrom(const Position& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Position::IsInitialized() const {

  return true;
}

void Position::Swap(Position* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Position::InternalSwap(Position* other) {
  std::swap(x_, other->x_);
  std::swap(y_, other->y_);
  std::swap(z_, other->z_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Position::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Position_descriptor_;
  metadata.reflection = Position_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Position

// optional double x = 1;
void Position::clear_x() {
  x_ = 0;
}
 double Position::x() const {
  // @@protoc_insertion_point(field_get:noninteracting.Position.x)
  return x_;
}
 void Position::set_x(double value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:noninteracting.Position.x)
}

// optional double y = 2;
void Position::clear_y() {
  y_ = 0;
}
 double Position::y() const {
  // @@protoc_insertion_point(field_get:noninteracting.Position.y)
  return y_;
}
 void Position::set_y(double value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:noninteracting.Position.y)
}

// optional double z = 3;
void Position::clear_z() {
  z_ = 0;
}
 double Position::z() const {
  // @@protoc_insertion_point(field_get:noninteracting.Position.z)
  return z_;
}
 void Position::set_z(double value) {
  
  z_ = value;
  // @@protoc_insertion_point(field_set:noninteracting.Position.z)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Edge::kFromJunctionIdFieldNumber;
const int Edge::kToJunctionIdFieldNumber;
const int Edge::kLengthFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Edge::Edge()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:noninteracting.Edge)
}

void Edge::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

Edge::Edge(const Edge& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:noninteracting.Edge)
}

void Edge::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  fromjunctionid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  tojunctionid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  length_ = 0;
}

Edge::~Edge() {
  // @@protoc_insertion_point(destructor:noninteracting.Edge)
  SharedDtor();
}

void Edge::SharedDtor() {
  fromjunctionid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  tojunctionid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void Edge::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Edge::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Edge_descriptor_;
}

const Edge& Edge::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_noninteracting_2eproto();
  return *default_instance_;
}

Edge* Edge::default_instance_ = NULL;

Edge* Edge::New(::google::protobuf::Arena* arena) const {
  Edge* n = new Edge;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Edge::Clear() {
  fromjunctionid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  tojunctionid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  length_ = 0;
}

bool Edge::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:noninteracting.Edge)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string fromJunctionId = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_fromjunctionid()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->fromjunctionid().data(), this->fromjunctionid().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "noninteracting.Edge.fromJunctionId"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_toJunctionId;
        break;
      }

      // optional string toJunctionId = 2;
      case 2: {
        if (tag == 18) {
         parse_toJunctionId:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_tojunctionid()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->tojunctionid().data(), this->tojunctionid().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "noninteracting.Edge.toJunctionId"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(25)) goto parse_length;
        break;
      }

      // optional double length = 3;
      case 3: {
        if (tag == 25) {
         parse_length:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &length_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:noninteracting.Edge)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:noninteracting.Edge)
  return false;
#undef DO_
}

void Edge::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:noninteracting.Edge)
  // optional string fromJunctionId = 1;
  if (this->fromjunctionid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->fromjunctionid().data(), this->fromjunctionid().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "noninteracting.Edge.fromJunctionId");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->fromjunctionid(), output);
  }

  // optional string toJunctionId = 2;
  if (this->tojunctionid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->tojunctionid().data(), this->tojunctionid().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "noninteracting.Edge.toJunctionId");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->tojunctionid(), output);
  }

  // optional double length = 3;
  if (this->length() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->length(), output);
  }

  // @@protoc_insertion_point(serialize_end:noninteracting.Edge)
}

::google::protobuf::uint8* Edge::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:noninteracting.Edge)
  // optional string fromJunctionId = 1;
  if (this->fromjunctionid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->fromjunctionid().data(), this->fromjunctionid().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "noninteracting.Edge.fromJunctionId");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->fromjunctionid(), target);
  }

  // optional string toJunctionId = 2;
  if (this->tojunctionid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->tojunctionid().data(), this->tojunctionid().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "noninteracting.Edge.toJunctionId");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->tojunctionid(), target);
  }

  // optional double length = 3;
  if (this->length() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(3, this->length(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:noninteracting.Edge)
  return target;
}

int Edge::ByteSize() const {
  int total_size = 0;

  // optional string fromJunctionId = 1;
  if (this->fromjunctionid().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->fromjunctionid());
  }

  // optional string toJunctionId = 2;
  if (this->tojunctionid().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->tojunctionid());
  }

  // optional double length = 3;
  if (this->length() != 0) {
    total_size += 1 + 8;
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Edge::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const Edge* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Edge>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Edge::MergeFrom(const Edge& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from.fromjunctionid().size() > 0) {

    fromjunctionid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.fromjunctionid_);
  }
  if (from.tojunctionid().size() > 0) {

    tojunctionid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.tojunctionid_);
  }
  if (from.length() != 0) {
    set_length(from.length());
  }
}

void Edge::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Edge::CopyFrom(const Edge& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Edge::IsInitialized() const {

  return true;
}

void Edge::Swap(Edge* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Edge::InternalSwap(Edge* other) {
  fromjunctionid_.Swap(&other->fromjunctionid_);
  tojunctionid_.Swap(&other->tojunctionid_);
  std::swap(length_, other->length_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Edge::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Edge_descriptor_;
  metadata.reflection = Edge_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Edge

// optional string fromJunctionId = 1;
void Edge::clear_fromjunctionid() {
  fromjunctionid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& Edge::fromjunctionid() const {
  // @@protoc_insertion_point(field_get:noninteracting.Edge.fromJunctionId)
  return fromjunctionid_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Edge::set_fromjunctionid(const ::std::string& value) {
  
  fromjunctionid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:noninteracting.Edge.fromJunctionId)
}
 void Edge::set_fromjunctionid(const char* value) {
  
  fromjunctionid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:noninteracting.Edge.fromJunctionId)
}
 void Edge::set_fromjunctionid(const char* value, size_t size) {
  
  fromjunctionid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:noninteracting.Edge.fromJunctionId)
}
 ::std::string* Edge::mutable_fromjunctionid() {
  
  // @@protoc_insertion_point(field_mutable:noninteracting.Edge.fromJunctionId)
  return fromjunctionid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* Edge::release_fromjunctionid() {
  
  return fromjunctionid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Edge::set_allocated_fromjunctionid(::std::string* fromjunctionid) {
  if (fromjunctionid != NULL) {
    
  } else {
    
  }
  fromjunctionid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), fromjunctionid);
  // @@protoc_insertion_point(field_set_allocated:noninteracting.Edge.fromJunctionId)
}

// optional string toJunctionId = 2;
void Edge::clear_tojunctionid() {
  tojunctionid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& Edge::tojunctionid() const {
  // @@protoc_insertion_point(field_get:noninteracting.Edge.toJunctionId)
  return tojunctionid_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Edge::set_tojunctionid(const ::std::string& value) {
  
  tojunctionid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:noninteracting.Edge.toJunctionId)
}
 void Edge::set_tojunctionid(const char* value) {
  
  tojunctionid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:noninteracting.Edge.toJunctionId)
}
 void Edge::set_tojunctionid(const char* value, size_t size) {
  
  tojunctionid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:noninteracting.Edge.toJunctionId)
}
 ::std::string* Edge::mutable_tojunctionid() {
  
  // @@protoc_insertion_point(field_mutable:noninteracting.Edge.toJunctionId)
  return tojunctionid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* Edge::release_tojunctionid() {
  
  return tojunctionid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Edge::set_allocated_tojunctionid(::std::string* tojunctionid) {
  if (tojunctionid != NULL) {
    
  } else {
    
  }
  tojunctionid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), tojunctionid);
  // @@protoc_insertion_point(field_set_allocated:noninteracting.Edge.toJunctionId)
}

// optional double length = 3;
void Edge::clear_length() {
  length_ = 0;
}
 double Edge::length() const {
  // @@protoc_insertion_point(field_get:noninteracting.Edge.length)
  return length_;
}
 void Edge::set_length(double value) {
  
  length_ = value;
  // @@protoc_insertion_point(field_set:noninteracting.Edge.length)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SUMOTime::kSumoTimeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SUMOTime::SUMOTime()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:noninteracting.SUMOTime)
}

void SUMOTime::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

SUMOTime::SUMOTime(const SUMOTime& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:noninteracting.SUMOTime)
}

void SUMOTime::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  sumotime_ = 0;
}

SUMOTime::~SUMOTime() {
  // @@protoc_insertion_point(destructor:noninteracting.SUMOTime)
  SharedDtor();
}

void SUMOTime::SharedDtor() {
  if (this != default_instance_) {
  }
}

void SUMOTime::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SUMOTime::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SUMOTime_descriptor_;
}

const SUMOTime& SUMOTime::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_noninteracting_2eproto();
  return *default_instance_;
}

SUMOTime* SUMOTime::default_instance_ = NULL;

SUMOTime* SUMOTime::New(::google::protobuf::Arena* arena) const {
  SUMOTime* n = new SUMOTime;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void SUMOTime::Clear() {
  sumotime_ = 0;
}

bool SUMOTime::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:noninteracting.SUMOTime)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional double sumoTime = 1;
      case 1: {
        if (tag == 9) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &sumotime_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:noninteracting.SUMOTime)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:noninteracting.SUMOTime)
  return false;
#undef DO_
}

void SUMOTime::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:noninteracting.SUMOTime)
  // optional double sumoTime = 1;
  if (this->sumotime() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(1, this->sumotime(), output);
  }

  // @@protoc_insertion_point(serialize_end:noninteracting.SUMOTime)
}

::google::protobuf::uint8* SUMOTime::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:noninteracting.SUMOTime)
  // optional double sumoTime = 1;
  if (this->sumotime() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(1, this->sumotime(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:noninteracting.SUMOTime)
  return target;
}

int SUMOTime::ByteSize() const {
  int total_size = 0;

  // optional double sumoTime = 1;
  if (this->sumotime() != 0) {
    total_size += 1 + 8;
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SUMOTime::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const SUMOTime* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const SUMOTime>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void SUMOTime::MergeFrom(const SUMOTime& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from.sumotime() != 0) {
    set_sumotime(from.sumotime());
  }
}

void SUMOTime::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SUMOTime::CopyFrom(const SUMOTime& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SUMOTime::IsInitialized() const {

  return true;
}

void SUMOTime::Swap(SUMOTime* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SUMOTime::InternalSwap(SUMOTime* other) {
  std::swap(sumotime_, other->sumotime_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata SUMOTime::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SUMOTime_descriptor_;
  metadata.reflection = SUMOTime_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// SUMOTime

// optional double sumoTime = 1;
void SUMOTime::clear_sumotime() {
  sumotime_ = 0;
}
 double SUMOTime::sumotime() const {
  // @@protoc_insertion_point(field_get:noninteracting.SUMOTime.sumoTime)
  return sumotime_;
}
 void SUMOTime::set_sumotime(double value) {
  
  sumotime_ = value;
  // @@protoc_insertion_point(field_set:noninteracting.SUMOTime.sumoTime)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SUMOReal::kSumoRealFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SUMOReal::SUMOReal()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:noninteracting.SUMOReal)
}

void SUMOReal::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

SUMOReal::SUMOReal(const SUMOReal& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:noninteracting.SUMOReal)
}

void SUMOReal::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  sumoreal_ = 0;
}

SUMOReal::~SUMOReal() {
  // @@protoc_insertion_point(destructor:noninteracting.SUMOReal)
  SharedDtor();
}

void SUMOReal::SharedDtor() {
  if (this != default_instance_) {
  }
}

void SUMOReal::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SUMOReal::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SUMOReal_descriptor_;
}

const SUMOReal& SUMOReal::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_noninteracting_2eproto();
  return *default_instance_;
}

SUMOReal* SUMOReal::default_instance_ = NULL;

SUMOReal* SUMOReal::New(::google::protobuf::Arena* arena) const {
  SUMOReal* n = new SUMOReal;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void SUMOReal::Clear() {
  sumoreal_ = 0;
}

bool SUMOReal::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:noninteracting.SUMOReal)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional double sumoReal = 1;
      case 1: {
        if (tag == 9) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &sumoreal_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:noninteracting.SUMOReal)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:noninteracting.SUMOReal)
  return false;
#undef DO_
}

void SUMOReal::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:noninteracting.SUMOReal)
  // optional double sumoReal = 1;
  if (this->sumoreal() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(1, this->sumoreal(), output);
  }

  // @@protoc_insertion_point(serialize_end:noninteracting.SUMOReal)
}

::google::protobuf::uint8* SUMOReal::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:noninteracting.SUMOReal)
  // optional double sumoReal = 1;
  if (this->sumoreal() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(1, this->sumoreal(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:noninteracting.SUMOReal)
  return target;
}

int SUMOReal::ByteSize() const {
  int total_size = 0;

  // optional double sumoReal = 1;
  if (this->sumoreal() != 0) {
    total_size += 1 + 8;
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SUMOReal::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const SUMOReal* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const SUMOReal>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void SUMOReal::MergeFrom(const SUMOReal& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from.sumoreal() != 0) {
    set_sumoreal(from.sumoreal());
  }
}

void SUMOReal::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SUMOReal::CopyFrom(const SUMOReal& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SUMOReal::IsInitialized() const {

  return true;
}

void SUMOReal::Swap(SUMOReal* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SUMOReal::InternalSwap(SUMOReal* other) {
  std::swap(sumoreal_, other->sumoreal_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata SUMOReal::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SUMOReal_descriptor_;
  metadata.reflection = SUMOReal_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// SUMOReal

// optional double sumoReal = 1;
void SUMOReal::clear_sumoreal() {
  sumoreal_ = 0;
}
 double SUMOReal::sumoreal() const {
  // @@protoc_insertion_point(field_get:noninteracting.SUMOReal.sumoReal)
  return sumoreal_;
}
 void SUMOReal::set_sumoreal(double value) {
  
  sumoreal_ = value;
  // @@protoc_insertion_point(field_set:noninteracting.SUMOReal.sumoReal)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int MSPersonStage_Walking::kEdgeFieldNumber;
const int MSPersonStage_Walking::kNextRouteEdgeFieldNumber;
const int MSPersonStage_Walking::kDepartPosFieldNumber;
const int MSPersonStage_Walking::kArrivalPosFieldNumber;
const int MSPersonStage_Walking::kMaxSpeedFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MSPersonStage_Walking::MSPersonStage_Walking()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:noninteracting.MSPersonStage_Walking)
}

void MSPersonStage_Walking::InitAsDefaultInstance() {
  _is_default_instance_ = true;
  edge_ = const_cast< ::noninteracting::Edge*>(&::noninteracting::Edge::default_instance());
  nextrouteedge_ = const_cast< ::noninteracting::Edge*>(&::noninteracting::Edge::default_instance());
}

MSPersonStage_Walking::MSPersonStage_Walking(const MSPersonStage_Walking& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:noninteracting.MSPersonStage_Walking)
}

void MSPersonStage_Walking::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  edge_ = NULL;
  nextrouteedge_ = NULL;
  departpos_ = 0;
  arrivalpos_ = 0;
  maxspeed_ = 0;
}

MSPersonStage_Walking::~MSPersonStage_Walking() {
  // @@protoc_insertion_point(destructor:noninteracting.MSPersonStage_Walking)
  SharedDtor();
}

void MSPersonStage_Walking::SharedDtor() {
  if (this != default_instance_) {
    delete edge_;
    delete nextrouteedge_;
  }
}

void MSPersonStage_Walking::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MSPersonStage_Walking::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MSPersonStage_Walking_descriptor_;
}

const MSPersonStage_Walking& MSPersonStage_Walking::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_noninteracting_2eproto();
  return *default_instance_;
}

MSPersonStage_Walking* MSPersonStage_Walking::default_instance_ = NULL;

MSPersonStage_Walking* MSPersonStage_Walking::New(::google::protobuf::Arena* arena) const {
  MSPersonStage_Walking* n = new MSPersonStage_Walking;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void MSPersonStage_Walking::Clear() {
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<MSPersonStage_Walking*>(16)->f)

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(departpos_, maxspeed_);
  if (GetArenaNoVirtual() == NULL && edge_ != NULL) delete edge_;
  edge_ = NULL;
  if (GetArenaNoVirtual() == NULL && nextrouteedge_ != NULL) delete nextrouteedge_;
  nextrouteedge_ = NULL;

#undef ZR_HELPER_
#undef ZR_

}

bool MSPersonStage_Walking::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:noninteracting.MSPersonStage_Walking)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .noninteracting.Edge edge = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_edge()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_nextRouteEdge;
        break;
      }

      // optional .noninteracting.Edge nextRouteEdge = 2;
      case 2: {
        if (tag == 18) {
         parse_nextRouteEdge:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_nextrouteedge()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(25)) goto parse_departPos;
        break;
      }

      // optional double departPos = 3;
      case 3: {
        if (tag == 25) {
         parse_departPos:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &departpos_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(33)) goto parse_arrivalPos;
        break;
      }

      // optional double arrivalPos = 4;
      case 4: {
        if (tag == 33) {
         parse_arrivalPos:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &arrivalpos_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(41)) goto parse_maxSpeed;
        break;
      }

      // optional double maxSpeed = 5;
      case 5: {
        if (tag == 41) {
         parse_maxSpeed:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &maxspeed_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:noninteracting.MSPersonStage_Walking)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:noninteracting.MSPersonStage_Walking)
  return false;
#undef DO_
}

void MSPersonStage_Walking::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:noninteracting.MSPersonStage_Walking)
  // optional .noninteracting.Edge edge = 1;
  if (this->has_edge()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->edge_, output);
  }

  // optional .noninteracting.Edge nextRouteEdge = 2;
  if (this->has_nextrouteedge()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *this->nextrouteedge_, output);
  }

  // optional double departPos = 3;
  if (this->departpos() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->departpos(), output);
  }

  // optional double arrivalPos = 4;
  if (this->arrivalpos() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(4, this->arrivalpos(), output);
  }

  // optional double maxSpeed = 5;
  if (this->maxspeed() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(5, this->maxspeed(), output);
  }

  // @@protoc_insertion_point(serialize_end:noninteracting.MSPersonStage_Walking)
}

::google::protobuf::uint8* MSPersonStage_Walking::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:noninteracting.MSPersonStage_Walking)
  // optional .noninteracting.Edge edge = 1;
  if (this->has_edge()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, *this->edge_, target);
  }

  // optional .noninteracting.Edge nextRouteEdge = 2;
  if (this->has_nextrouteedge()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, *this->nextrouteedge_, target);
  }

  // optional double departPos = 3;
  if (this->departpos() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(3, this->departpos(), target);
  }

  // optional double arrivalPos = 4;
  if (this->arrivalpos() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(4, this->arrivalpos(), target);
  }

  // optional double maxSpeed = 5;
  if (this->maxspeed() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(5, this->maxspeed(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:noninteracting.MSPersonStage_Walking)
  return target;
}

int MSPersonStage_Walking::ByteSize() const {
  int total_size = 0;

  // optional .noninteracting.Edge edge = 1;
  if (this->has_edge()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->edge_);
  }

  // optional .noninteracting.Edge nextRouteEdge = 2;
  if (this->has_nextrouteedge()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->nextrouteedge_);
  }

  // optional double departPos = 3;
  if (this->departpos() != 0) {
    total_size += 1 + 8;
  }

  // optional double arrivalPos = 4;
  if (this->arrivalpos() != 0) {
    total_size += 1 + 8;
  }

  // optional double maxSpeed = 5;
  if (this->maxspeed() != 0) {
    total_size += 1 + 8;
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MSPersonStage_Walking::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const MSPersonStage_Walking* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const MSPersonStage_Walking>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MSPersonStage_Walking::MergeFrom(const MSPersonStage_Walking& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from.has_edge()) {
    mutable_edge()->::noninteracting::Edge::MergeFrom(from.edge());
  }
  if (from.has_nextrouteedge()) {
    mutable_nextrouteedge()->::noninteracting::Edge::MergeFrom(from.nextrouteedge());
  }
  if (from.departpos() != 0) {
    set_departpos(from.departpos());
  }
  if (from.arrivalpos() != 0) {
    set_arrivalpos(from.arrivalpos());
  }
  if (from.maxspeed() != 0) {
    set_maxspeed(from.maxspeed());
  }
}

void MSPersonStage_Walking::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MSPersonStage_Walking::CopyFrom(const MSPersonStage_Walking& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MSPersonStage_Walking::IsInitialized() const {

  return true;
}

void MSPersonStage_Walking::Swap(MSPersonStage_Walking* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MSPersonStage_Walking::InternalSwap(MSPersonStage_Walking* other) {
  std::swap(edge_, other->edge_);
  std::swap(nextrouteedge_, other->nextrouteedge_);
  std::swap(departpos_, other->departpos_);
  std::swap(arrivalpos_, other->arrivalpos_);
  std::swap(maxspeed_, other->maxspeed_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata MSPersonStage_Walking::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MSPersonStage_Walking_descriptor_;
  metadata.reflection = MSPersonStage_Walking_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// MSPersonStage_Walking

// optional .noninteracting.Edge edge = 1;
bool MSPersonStage_Walking::has_edge() const {
  return !_is_default_instance_ && edge_ != NULL;
}
void MSPersonStage_Walking::clear_edge() {
  if (GetArenaNoVirtual() == NULL && edge_ != NULL) delete edge_;
  edge_ = NULL;
}
const ::noninteracting::Edge& MSPersonStage_Walking::edge() const {
  // @@protoc_insertion_point(field_get:noninteracting.MSPersonStage_Walking.edge)
  return edge_ != NULL ? *edge_ : *default_instance_->edge_;
}
::noninteracting::Edge* MSPersonStage_Walking::mutable_edge() {
  
  if (edge_ == NULL) {
    edge_ = new ::noninteracting::Edge;
  }
  // @@protoc_insertion_point(field_mutable:noninteracting.MSPersonStage_Walking.edge)
  return edge_;
}
::noninteracting::Edge* MSPersonStage_Walking::release_edge() {
  
  ::noninteracting::Edge* temp = edge_;
  edge_ = NULL;
  return temp;
}
void MSPersonStage_Walking::set_allocated_edge(::noninteracting::Edge* edge) {
  delete edge_;
  edge_ = edge;
  if (edge) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:noninteracting.MSPersonStage_Walking.edge)
}

// optional .noninteracting.Edge nextRouteEdge = 2;
bool MSPersonStage_Walking::has_nextrouteedge() const {
  return !_is_default_instance_ && nextrouteedge_ != NULL;
}
void MSPersonStage_Walking::clear_nextrouteedge() {
  if (GetArenaNoVirtual() == NULL && nextrouteedge_ != NULL) delete nextrouteedge_;
  nextrouteedge_ = NULL;
}
const ::noninteracting::Edge& MSPersonStage_Walking::nextrouteedge() const {
  // @@protoc_insertion_point(field_get:noninteracting.MSPersonStage_Walking.nextRouteEdge)
  return nextrouteedge_ != NULL ? *nextrouteedge_ : *default_instance_->nextrouteedge_;
}
::noninteracting::Edge* MSPersonStage_Walking::mutable_nextrouteedge() {
  
  if (nextrouteedge_ == NULL) {
    nextrouteedge_ = new ::noninteracting::Edge;
  }
  // @@protoc_insertion_point(field_mutable:noninteracting.MSPersonStage_Walking.nextRouteEdge)
  return nextrouteedge_;
}
::noninteracting::Edge* MSPersonStage_Walking::release_nextrouteedge() {
  
  ::noninteracting::Edge* temp = nextrouteedge_;
  nextrouteedge_ = NULL;
  return temp;
}
void MSPersonStage_Walking::set_allocated_nextrouteedge(::noninteracting::Edge* nextrouteedge) {
  delete nextrouteedge_;
  nextrouteedge_ = nextrouteedge;
  if (nextrouteedge) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:noninteracting.MSPersonStage_Walking.nextRouteEdge)
}

// optional double departPos = 3;
void MSPersonStage_Walking::clear_departpos() {
  departpos_ = 0;
}
 double MSPersonStage_Walking::departpos() const {
  // @@protoc_insertion_point(field_get:noninteracting.MSPersonStage_Walking.departPos)
  return departpos_;
}
 void MSPersonStage_Walking::set_departpos(double value) {
  
  departpos_ = value;
  // @@protoc_insertion_point(field_set:noninteracting.MSPersonStage_Walking.departPos)
}

// optional double arrivalPos = 4;
void MSPersonStage_Walking::clear_arrivalpos() {
  arrivalpos_ = 0;
}
 double MSPersonStage_Walking::arrivalpos() const {
  // @@protoc_insertion_point(field_get:noninteracting.MSPersonStage_Walking.arrivalPos)
  return arrivalpos_;
}
 void MSPersonStage_Walking::set_arrivalpos(double value) {
  
  arrivalpos_ = value;
  // @@protoc_insertion_point(field_set:noninteracting.MSPersonStage_Walking.arrivalPos)
}

// optional double maxSpeed = 5;
void MSPersonStage_Walking::clear_maxspeed() {
  maxspeed_ = 0;
}
 double MSPersonStage_Walking::maxspeed() const {
  // @@protoc_insertion_point(field_get:noninteracting.MSPersonStage_Walking.maxSpeed)
  return maxspeed_;
}
 void MSPersonStage_Walking::set_maxspeed(double value) {
  
  maxspeed_ = value;
  // @@protoc_insertion_point(field_set:noninteracting.MSPersonStage_Walking.maxSpeed)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CMPWlkgTm::kEdgeFieldNumber;
const int CMPWlkgTm::kStageFieldNumber;
const int CMPWlkgTm::kSumoTimeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CMPWlkgTm::CMPWlkgTm()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:noninteracting.CMPWlkgTm)
}

void CMPWlkgTm::InitAsDefaultInstance() {
  _is_default_instance_ = true;
  edge_ = const_cast< ::noninteracting::Edge*>(&::noninteracting::Edge::default_instance());
  stage_ = const_cast< ::noninteracting::MSPersonStage_Walking*>(&::noninteracting::MSPersonStage_Walking::default_instance());
  sumotime_ = const_cast< ::noninteracting::SUMOTime*>(&::noninteracting::SUMOTime::default_instance());
}

CMPWlkgTm::CMPWlkgTm(const CMPWlkgTm& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:noninteracting.CMPWlkgTm)
}

void CMPWlkgTm::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  edge_ = NULL;
  stage_ = NULL;
  sumotime_ = NULL;
}

CMPWlkgTm::~CMPWlkgTm() {
  // @@protoc_insertion_point(destructor:noninteracting.CMPWlkgTm)
  SharedDtor();
}

void CMPWlkgTm::SharedDtor() {
  if (this != default_instance_) {
    delete edge_;
    delete stage_;
    delete sumotime_;
  }
}

void CMPWlkgTm::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CMPWlkgTm::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CMPWlkgTm_descriptor_;
}

const CMPWlkgTm& CMPWlkgTm::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_noninteracting_2eproto();
  return *default_instance_;
}

CMPWlkgTm* CMPWlkgTm::default_instance_ = NULL;

CMPWlkgTm* CMPWlkgTm::New(::google::protobuf::Arena* arena) const {
  CMPWlkgTm* n = new CMPWlkgTm;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void CMPWlkgTm::Clear() {
  if (GetArenaNoVirtual() == NULL && edge_ != NULL) delete edge_;
  edge_ = NULL;
  if (GetArenaNoVirtual() == NULL && stage_ != NULL) delete stage_;
  stage_ = NULL;
  if (GetArenaNoVirtual() == NULL && sumotime_ != NULL) delete sumotime_;
  sumotime_ = NULL;
}

bool CMPWlkgTm::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:noninteracting.CMPWlkgTm)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .noninteracting.Edge edge = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_edge()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_stage;
        break;
      }

      // optional .noninteracting.MSPersonStage_Walking stage = 2;
      case 2: {
        if (tag == 18) {
         parse_stage:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_stage()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_sumoTime;
        break;
      }

      // optional .noninteracting.SUMOTime sumoTime = 3;
      case 3: {
        if (tag == 26) {
         parse_sumoTime:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_sumotime()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:noninteracting.CMPWlkgTm)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:noninteracting.CMPWlkgTm)
  return false;
#undef DO_
}

void CMPWlkgTm::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:noninteracting.CMPWlkgTm)
  // optional .noninteracting.Edge edge = 1;
  if (this->has_edge()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->edge_, output);
  }

  // optional .noninteracting.MSPersonStage_Walking stage = 2;
  if (this->has_stage()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *this->stage_, output);
  }

  // optional .noninteracting.SUMOTime sumoTime = 3;
  if (this->has_sumotime()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, *this->sumotime_, output);
  }

  // @@protoc_insertion_point(serialize_end:noninteracting.CMPWlkgTm)
}

::google::protobuf::uint8* CMPWlkgTm::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:noninteracting.CMPWlkgTm)
  // optional .noninteracting.Edge edge = 1;
  if (this->has_edge()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, *this->edge_, target);
  }

  // optional .noninteracting.MSPersonStage_Walking stage = 2;
  if (this->has_stage()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, *this->stage_, target);
  }

  // optional .noninteracting.SUMOTime sumoTime = 3;
  if (this->has_sumotime()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, *this->sumotime_, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:noninteracting.CMPWlkgTm)
  return target;
}

int CMPWlkgTm::ByteSize() const {
  int total_size = 0;

  // optional .noninteracting.Edge edge = 1;
  if (this->has_edge()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->edge_);
  }

  // optional .noninteracting.MSPersonStage_Walking stage = 2;
  if (this->has_stage()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->stage_);
  }

  // optional .noninteracting.SUMOTime sumoTime = 3;
  if (this->has_sumotime()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->sumotime_);
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CMPWlkgTm::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const CMPWlkgTm* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const CMPWlkgTm>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CMPWlkgTm::MergeFrom(const CMPWlkgTm& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from.has_edge()) {
    mutable_edge()->::noninteracting::Edge::MergeFrom(from.edge());
  }
  if (from.has_stage()) {
    mutable_stage()->::noninteracting::MSPersonStage_Walking::MergeFrom(from.stage());
  }
  if (from.has_sumotime()) {
    mutable_sumotime()->::noninteracting::SUMOTime::MergeFrom(from.sumotime());
  }
}

void CMPWlkgTm::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CMPWlkgTm::CopyFrom(const CMPWlkgTm& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CMPWlkgTm::IsInitialized() const {

  return true;
}

void CMPWlkgTm::Swap(CMPWlkgTm* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CMPWlkgTm::InternalSwap(CMPWlkgTm* other) {
  std::swap(edge_, other->edge_);
  std::swap(stage_, other->stage_);
  std::swap(sumotime_, other->sumotime_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata CMPWlkgTm::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CMPWlkgTm_descriptor_;
  metadata.reflection = CMPWlkgTm_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// CMPWlkgTm

// optional .noninteracting.Edge edge = 1;
bool CMPWlkgTm::has_edge() const {
  return !_is_default_instance_ && edge_ != NULL;
}
void CMPWlkgTm::clear_edge() {
  if (GetArenaNoVirtual() == NULL && edge_ != NULL) delete edge_;
  edge_ = NULL;
}
const ::noninteracting::Edge& CMPWlkgTm::edge() const {
  // @@protoc_insertion_point(field_get:noninteracting.CMPWlkgTm.edge)
  return edge_ != NULL ? *edge_ : *default_instance_->edge_;
}
::noninteracting::Edge* CMPWlkgTm::mutable_edge() {
  
  if (edge_ == NULL) {
    edge_ = new ::noninteracting::Edge;
  }
  // @@protoc_insertion_point(field_mutable:noninteracting.CMPWlkgTm.edge)
  return edge_;
}
::noninteracting::Edge* CMPWlkgTm::release_edge() {
  
  ::noninteracting::Edge* temp = edge_;
  edge_ = NULL;
  return temp;
}
void CMPWlkgTm::set_allocated_edge(::noninteracting::Edge* edge) {
  delete edge_;
  edge_ = edge;
  if (edge) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:noninteracting.CMPWlkgTm.edge)
}

// optional .noninteracting.MSPersonStage_Walking stage = 2;
bool CMPWlkgTm::has_stage() const {
  return !_is_default_instance_ && stage_ != NULL;
}
void CMPWlkgTm::clear_stage() {
  if (GetArenaNoVirtual() == NULL && stage_ != NULL) delete stage_;
  stage_ = NULL;
}
const ::noninteracting::MSPersonStage_Walking& CMPWlkgTm::stage() const {
  // @@protoc_insertion_point(field_get:noninteracting.CMPWlkgTm.stage)
  return stage_ != NULL ? *stage_ : *default_instance_->stage_;
}
::noninteracting::MSPersonStage_Walking* CMPWlkgTm::mutable_stage() {
  
  if (stage_ == NULL) {
    stage_ = new ::noninteracting::MSPersonStage_Walking;
  }
  // @@protoc_insertion_point(field_mutable:noninteracting.CMPWlkgTm.stage)
  return stage_;
}
::noninteracting::MSPersonStage_Walking* CMPWlkgTm::release_stage() {
  
  ::noninteracting::MSPersonStage_Walking* temp = stage_;
  stage_ = NULL;
  return temp;
}
void CMPWlkgTm::set_allocated_stage(::noninteracting::MSPersonStage_Walking* stage) {
  delete stage_;
  stage_ = stage;
  if (stage) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:noninteracting.CMPWlkgTm.stage)
}

// optional .noninteracting.SUMOTime sumoTime = 3;
bool CMPWlkgTm::has_sumotime() const {
  return !_is_default_instance_ && sumotime_ != NULL;
}
void CMPWlkgTm::clear_sumotime() {
  if (GetArenaNoVirtual() == NULL && sumotime_ != NULL) delete sumotime_;
  sumotime_ = NULL;
}
const ::noninteracting::SUMOTime& CMPWlkgTm::sumotime() const {
  // @@protoc_insertion_point(field_get:noninteracting.CMPWlkgTm.sumoTime)
  return sumotime_ != NULL ? *sumotime_ : *default_instance_->sumotime_;
}
::noninteracting::SUMOTime* CMPWlkgTm::mutable_sumotime() {
  
  if (sumotime_ == NULL) {
    sumotime_ = new ::noninteracting::SUMOTime;
  }
  // @@protoc_insertion_point(field_mutable:noninteracting.CMPWlkgTm.sumoTime)
  return sumotime_;
}
::noninteracting::SUMOTime* CMPWlkgTm::release_sumotime() {
  
  ::noninteracting::SUMOTime* temp = sumotime_;
  sumotime_ = NULL;
  return temp;
}
void CMPWlkgTm::set_allocated_sumotime(::noninteracting::SUMOTime* sumotime) {
  delete sumotime_;
  sumotime_ = sumotime;
  if (sumotime) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:noninteracting.CMPWlkgTm.sumoTime)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GetPos::kStageFieldNumber;
const int GetPos::kSumoTimeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GetPos::GetPos()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:noninteracting.GetPos)
}

void GetPos::InitAsDefaultInstance() {
  _is_default_instance_ = true;
  stage_ = const_cast< ::noninteracting::MSPersonStage_Walking*>(&::noninteracting::MSPersonStage_Walking::default_instance());
  sumotime_ = const_cast< ::noninteracting::SUMOTime*>(&::noninteracting::SUMOTime::default_instance());
}

GetPos::GetPos(const GetPos& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:noninteracting.GetPos)
}

void GetPos::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  stage_ = NULL;
  sumotime_ = NULL;
}

GetPos::~GetPos() {
  // @@protoc_insertion_point(destructor:noninteracting.GetPos)
  SharedDtor();
}

void GetPos::SharedDtor() {
  if (this != default_instance_) {
    delete stage_;
    delete sumotime_;
  }
}

void GetPos::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* GetPos::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return GetPos_descriptor_;
}

const GetPos& GetPos::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_noninteracting_2eproto();
  return *default_instance_;
}

GetPos* GetPos::default_instance_ = NULL;

GetPos* GetPos::New(::google::protobuf::Arena* arena) const {
  GetPos* n = new GetPos;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void GetPos::Clear() {
  if (GetArenaNoVirtual() == NULL && stage_ != NULL) delete stage_;
  stage_ = NULL;
  if (GetArenaNoVirtual() == NULL && sumotime_ != NULL) delete sumotime_;
  sumotime_ = NULL;
}

bool GetPos::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:noninteracting.GetPos)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .noninteracting.MSPersonStage_Walking stage = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_stage()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_sumoTime;
        break;
      }

      // optional .noninteracting.SUMOTime sumoTime = 2;
      case 2: {
        if (tag == 18) {
         parse_sumoTime:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_sumotime()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:noninteracting.GetPos)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:noninteracting.GetPos)
  return false;
#undef DO_
}

void GetPos::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:noninteracting.GetPos)
  // optional .noninteracting.MSPersonStage_Walking stage = 1;
  if (this->has_stage()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->stage_, output);
  }

  // optional .noninteracting.SUMOTime sumoTime = 2;
  if (this->has_sumotime()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *this->sumotime_, output);
  }

  // @@protoc_insertion_point(serialize_end:noninteracting.GetPos)
}

::google::protobuf::uint8* GetPos::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:noninteracting.GetPos)
  // optional .noninteracting.MSPersonStage_Walking stage = 1;
  if (this->has_stage()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, *this->stage_, target);
  }

  // optional .noninteracting.SUMOTime sumoTime = 2;
  if (this->has_sumotime()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, *this->sumotime_, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:noninteracting.GetPos)
  return target;
}

int GetPos::ByteSize() const {
  int total_size = 0;

  // optional .noninteracting.MSPersonStage_Walking stage = 1;
  if (this->has_stage()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->stage_);
  }

  // optional .noninteracting.SUMOTime sumoTime = 2;
  if (this->has_sumotime()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->sumotime_);
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void GetPos::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const GetPos* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const GetPos>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void GetPos::MergeFrom(const GetPos& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from.has_stage()) {
    mutable_stage()->::noninteracting::MSPersonStage_Walking::MergeFrom(from.stage());
  }
  if (from.has_sumotime()) {
    mutable_sumotime()->::noninteracting::SUMOTime::MergeFrom(from.sumotime());
  }
}

void GetPos::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GetPos::CopyFrom(const GetPos& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetPos::IsInitialized() const {

  return true;
}

void GetPos::Swap(GetPos* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GetPos::InternalSwap(GetPos* other) {
  std::swap(stage_, other->stage_);
  std::swap(sumotime_, other->sumotime_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata GetPos::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = GetPos_descriptor_;
  metadata.reflection = GetPos_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// GetPos

// optional .noninteracting.MSPersonStage_Walking stage = 1;
bool GetPos::has_stage() const {
  return !_is_default_instance_ && stage_ != NULL;
}
void GetPos::clear_stage() {
  if (GetArenaNoVirtual() == NULL && stage_ != NULL) delete stage_;
  stage_ = NULL;
}
const ::noninteracting::MSPersonStage_Walking& GetPos::stage() const {
  // @@protoc_insertion_point(field_get:noninteracting.GetPos.stage)
  return stage_ != NULL ? *stage_ : *default_instance_->stage_;
}
::noninteracting::MSPersonStage_Walking* GetPos::mutable_stage() {
  
  if (stage_ == NULL) {
    stage_ = new ::noninteracting::MSPersonStage_Walking;
  }
  // @@protoc_insertion_point(field_mutable:noninteracting.GetPos.stage)
  return stage_;
}
::noninteracting::MSPersonStage_Walking* GetPos::release_stage() {
  
  ::noninteracting::MSPersonStage_Walking* temp = stage_;
  stage_ = NULL;
  return temp;
}
void GetPos::set_allocated_stage(::noninteracting::MSPersonStage_Walking* stage) {
  delete stage_;
  stage_ = stage;
  if (stage) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:noninteracting.GetPos.stage)
}

// optional .noninteracting.SUMOTime sumoTime = 2;
bool GetPos::has_sumotime() const {
  return !_is_default_instance_ && sumotime_ != NULL;
}
void GetPos::clear_sumotime() {
  if (GetArenaNoVirtual() == NULL && sumotime_ != NULL) delete sumotime_;
  sumotime_ = NULL;
}
const ::noninteracting::SUMOTime& GetPos::sumotime() const {
  // @@protoc_insertion_point(field_get:noninteracting.GetPos.sumoTime)
  return sumotime_ != NULL ? *sumotime_ : *default_instance_->sumotime_;
}
::noninteracting::SUMOTime* GetPos::mutable_sumotime() {
  
  if (sumotime_ == NULL) {
    sumotime_ = new ::noninteracting::SUMOTime;
  }
  // @@protoc_insertion_point(field_mutable:noninteracting.GetPos.sumoTime)
  return sumotime_;
}
::noninteracting::SUMOTime* GetPos::release_sumotime() {
  
  ::noninteracting::SUMOTime* temp = sumotime_;
  sumotime_ = NULL;
  return temp;
}
void GetPos::set_allocated_sumotime(::noninteracting::SUMOTime* sumotime) {
  delete sumotime_;
  sumotime_ = sumotime;
  if (sumotime) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:noninteracting.GetPos.sumoTime)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GetAngle::kStageFieldNumber;
const int GetAngle::kSumoTimeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GetAngle::GetAngle()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:noninteracting.GetAngle)
}

void GetAngle::InitAsDefaultInstance() {
  _is_default_instance_ = true;
  stage_ = const_cast< ::noninteracting::MSPersonStage_Walking*>(&::noninteracting::MSPersonStage_Walking::default_instance());
  sumotime_ = const_cast< ::noninteracting::SUMOTime*>(&::noninteracting::SUMOTime::default_instance());
}

GetAngle::GetAngle(const GetAngle& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:noninteracting.GetAngle)
}

void GetAngle::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  stage_ = NULL;
  sumotime_ = NULL;
}

GetAngle::~GetAngle() {
  // @@protoc_insertion_point(destructor:noninteracting.GetAngle)
  SharedDtor();
}

void GetAngle::SharedDtor() {
  if (this != default_instance_) {
    delete stage_;
    delete sumotime_;
  }
}

void GetAngle::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* GetAngle::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return GetAngle_descriptor_;
}

const GetAngle& GetAngle::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_noninteracting_2eproto();
  return *default_instance_;
}

GetAngle* GetAngle::default_instance_ = NULL;

GetAngle* GetAngle::New(::google::protobuf::Arena* arena) const {
  GetAngle* n = new GetAngle;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void GetAngle::Clear() {
  if (GetArenaNoVirtual() == NULL && stage_ != NULL) delete stage_;
  stage_ = NULL;
  if (GetArenaNoVirtual() == NULL && sumotime_ != NULL) delete sumotime_;
  sumotime_ = NULL;
}

bool GetAngle::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:noninteracting.GetAngle)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .noninteracting.MSPersonStage_Walking stage = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_stage()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_sumoTime;
        break;
      }

      // optional .noninteracting.SUMOTime sumoTime = 2;
      case 2: {
        if (tag == 18) {
         parse_sumoTime:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_sumotime()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:noninteracting.GetAngle)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:noninteracting.GetAngle)
  return false;
#undef DO_
}

void GetAngle::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:noninteracting.GetAngle)
  // optional .noninteracting.MSPersonStage_Walking stage = 1;
  if (this->has_stage()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->stage_, output);
  }

  // optional .noninteracting.SUMOTime sumoTime = 2;
  if (this->has_sumotime()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *this->sumotime_, output);
  }

  // @@protoc_insertion_point(serialize_end:noninteracting.GetAngle)
}

::google::protobuf::uint8* GetAngle::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:noninteracting.GetAngle)
  // optional .noninteracting.MSPersonStage_Walking stage = 1;
  if (this->has_stage()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, *this->stage_, target);
  }

  // optional .noninteracting.SUMOTime sumoTime = 2;
  if (this->has_sumotime()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, *this->sumotime_, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:noninteracting.GetAngle)
  return target;
}

int GetAngle::ByteSize() const {
  int total_size = 0;

  // optional .noninteracting.MSPersonStage_Walking stage = 1;
  if (this->has_stage()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->stage_);
  }

  // optional .noninteracting.SUMOTime sumoTime = 2;
  if (this->has_sumotime()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->sumotime_);
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void GetAngle::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const GetAngle* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const GetAngle>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void GetAngle::MergeFrom(const GetAngle& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from.has_stage()) {
    mutable_stage()->::noninteracting::MSPersonStage_Walking::MergeFrom(from.stage());
  }
  if (from.has_sumotime()) {
    mutable_sumotime()->::noninteracting::SUMOTime::MergeFrom(from.sumotime());
  }
}

void GetAngle::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GetAngle::CopyFrom(const GetAngle& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetAngle::IsInitialized() const {

  return true;
}

void GetAngle::Swap(GetAngle* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GetAngle::InternalSwap(GetAngle* other) {
  std::swap(stage_, other->stage_);
  std::swap(sumotime_, other->sumotime_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata GetAngle::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = GetAngle_descriptor_;
  metadata.reflection = GetAngle_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// GetAngle

// optional .noninteracting.MSPersonStage_Walking stage = 1;
bool GetAngle::has_stage() const {
  return !_is_default_instance_ && stage_ != NULL;
}
void GetAngle::clear_stage() {
  if (GetArenaNoVirtual() == NULL && stage_ != NULL) delete stage_;
  stage_ = NULL;
}
const ::noninteracting::MSPersonStage_Walking& GetAngle::stage() const {
  // @@protoc_insertion_point(field_get:noninteracting.GetAngle.stage)
  return stage_ != NULL ? *stage_ : *default_instance_->stage_;
}
::noninteracting::MSPersonStage_Walking* GetAngle::mutable_stage() {
  
  if (stage_ == NULL) {
    stage_ = new ::noninteracting::MSPersonStage_Walking;
  }
  // @@protoc_insertion_point(field_mutable:noninteracting.GetAngle.stage)
  return stage_;
}
::noninteracting::MSPersonStage_Walking* GetAngle::release_stage() {
  
  ::noninteracting::MSPersonStage_Walking* temp = stage_;
  stage_ = NULL;
  return temp;
}
void GetAngle::set_allocated_stage(::noninteracting::MSPersonStage_Walking* stage) {
  delete stage_;
  stage_ = stage;
  if (stage) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:noninteracting.GetAngle.stage)
}

// optional .noninteracting.SUMOTime sumoTime = 2;
bool GetAngle::has_sumotime() const {
  return !_is_default_instance_ && sumotime_ != NULL;
}
void GetAngle::clear_sumotime() {
  if (GetArenaNoVirtual() == NULL && sumotime_ != NULL) delete sumotime_;
  sumotime_ = NULL;
}
const ::noninteracting::SUMOTime& GetAngle::sumotime() const {
  // @@protoc_insertion_point(field_get:noninteracting.GetAngle.sumoTime)
  return sumotime_ != NULL ? *sumotime_ : *default_instance_->sumotime_;
}
::noninteracting::SUMOTime* GetAngle::mutable_sumotime() {
  
  if (sumotime_ == NULL) {
    sumotime_ = new ::noninteracting::SUMOTime;
  }
  // @@protoc_insertion_point(field_mutable:noninteracting.GetAngle.sumoTime)
  return sumotime_;
}
::noninteracting::SUMOTime* GetAngle::release_sumotime() {
  
  ::noninteracting::SUMOTime* temp = sumotime_;
  sumotime_ = NULL;
  return temp;
}
void GetAngle::set_allocated_sumotime(::noninteracting::SUMOTime* sumotime) {
  delete sumotime_;
  sumotime_ = sumotime;
  if (sumotime) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:noninteracting.GetAngle.sumoTime)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace noninteracting

// @@protoc_insertion_point(global_scope)
