// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: noninteracting.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "noninteracting.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace noninteracting {

namespace {

const ::google::protobuf::Descriptor* GetEdgePos_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  GetEdgePos_reflection_ = NULL;
const ::google::protobuf::Descriptor* PBEdge_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PBEdge_reflection_ = NULL;
const ::google::protobuf::Descriptor* PBSUMOTime_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PBSUMOTime_reflection_ = NULL;
const ::google::protobuf::Descriptor* PBSUMOReal_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PBSUMOReal_reflection_ = NULL;
const ::google::protobuf::Descriptor* PBMSPersonStage_Walking_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PBMSPersonStage_Walking_reflection_ = NULL;
const ::google::protobuf::Descriptor* CMPWlkgTm_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CMPWlkgTm_reflection_ = NULL;
const ::google::protobuf::Descriptor* CMPWlkgTmRpl_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CMPWlkgTmRpl_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_noninteracting_2eproto() {
  protobuf_AddDesc_noninteracting_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "noninteracting.proto");
  GOOGLE_CHECK(file != NULL);
  GetEdgePos_descriptor_ = file->message_type(0);
  static const int GetEdgePos_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetEdgePos, mycurrentbeginpos_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetEdgePos, mycurrentendpos_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetEdgePos, mycurrentduration_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetEdgePos, time_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetEdgePos, mylastentrytime_),
  };
  GetEdgePos_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      GetEdgePos_descriptor_,
      GetEdgePos::default_instance_,
      GetEdgePos_offsets_,
      -1,
      -1,
      -1,
      sizeof(GetEdgePos),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetEdgePos, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetEdgePos, _is_default_instance_));
  PBEdge_descriptor_ = file->message_type(1);
  static const int PBEdge_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBEdge, fromjunctionid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBEdge, tojunctionid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBEdge, length_),
  };
  PBEdge_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      PBEdge_descriptor_,
      PBEdge::default_instance_,
      PBEdge_offsets_,
      -1,
      -1,
      -1,
      sizeof(PBEdge),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBEdge, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBEdge, _is_default_instance_));
  PBSUMOTime_descriptor_ = file->message_type(2);
  static const int PBSUMOTime_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBSUMOTime, sumotime_),
  };
  PBSUMOTime_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      PBSUMOTime_descriptor_,
      PBSUMOTime::default_instance_,
      PBSUMOTime_offsets_,
      -1,
      -1,
      -1,
      sizeof(PBSUMOTime),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBSUMOTime, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBSUMOTime, _is_default_instance_));
  PBSUMOReal_descriptor_ = file->message_type(3);
  static const int PBSUMOReal_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBSUMOReal, sumoreal_),
  };
  PBSUMOReal_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      PBSUMOReal_descriptor_,
      PBSUMOReal::default_instance_,
      PBSUMOReal_offsets_,
      -1,
      -1,
      -1,
      sizeof(PBSUMOReal),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBSUMOReal, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBSUMOReal, _is_default_instance_));
  PBMSPersonStage_Walking_descriptor_ = file->message_type(4);
  static const int PBMSPersonStage_Walking_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBMSPersonStage_Walking, edge_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBMSPersonStage_Walking, nextrouteedge_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBMSPersonStage_Walking, departpos_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBMSPersonStage_Walking, arrivalpos_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBMSPersonStage_Walking, maxspeed_),
  };
  PBMSPersonStage_Walking_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      PBMSPersonStage_Walking_descriptor_,
      PBMSPersonStage_Walking::default_instance_,
      PBMSPersonStage_Walking_offsets_,
      -1,
      -1,
      -1,
      sizeof(PBMSPersonStage_Walking),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBMSPersonStage_Walking, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBMSPersonStage_Walking, _is_default_instance_));
  CMPWlkgTm_descriptor_ = file->message_type(5);
  static const int CMPWlkgTm_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CMPWlkgTm, prev_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CMPWlkgTm, stage_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CMPWlkgTm, sumotime_),
  };
  CMPWlkgTm_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      CMPWlkgTm_descriptor_,
      CMPWlkgTm::default_instance_,
      CMPWlkgTm_offsets_,
      -1,
      -1,
      -1,
      sizeof(CMPWlkgTm),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CMPWlkgTm, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CMPWlkgTm, _is_default_instance_));
  CMPWlkgTmRpl_descriptor_ = file->message_type(6);
  static const int CMPWlkgTmRpl_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CMPWlkgTmRpl, duration_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CMPWlkgTmRpl, mylastentrytime_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CMPWlkgTmRpl, mycurrentbeginpos_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CMPWlkgTmRpl, mycurrentendpos_),
  };
  CMPWlkgTmRpl_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      CMPWlkgTmRpl_descriptor_,
      CMPWlkgTmRpl::default_instance_,
      CMPWlkgTmRpl_offsets_,
      -1,
      -1,
      -1,
      sizeof(CMPWlkgTmRpl),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CMPWlkgTmRpl, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CMPWlkgTmRpl, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_noninteracting_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      GetEdgePos_descriptor_, &GetEdgePos::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      PBEdge_descriptor_, &PBEdge::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      PBSUMOTime_descriptor_, &PBSUMOTime::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      PBSUMOReal_descriptor_, &PBSUMOReal::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      PBMSPersonStage_Walking_descriptor_, &PBMSPersonStage_Walking::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      CMPWlkgTm_descriptor_, &CMPWlkgTm::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      CMPWlkgTmRpl_descriptor_, &CMPWlkgTmRpl::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_noninteracting_2eproto() {
  delete GetEdgePos::default_instance_;
  delete GetEdgePos_reflection_;
  delete PBEdge::default_instance_;
  delete PBEdge_reflection_;
  delete PBSUMOTime::default_instance_;
  delete PBSUMOTime_reflection_;
  delete PBSUMOReal::default_instance_;
  delete PBSUMOReal_reflection_;
  delete PBMSPersonStage_Walking::default_instance_;
  delete PBMSPersonStage_Walking_reflection_;
  delete CMPWlkgTm::default_instance_;
  delete CMPWlkgTm_reflection_;
  delete CMPWlkgTmRpl::default_instance_;
  delete CMPWlkgTmRpl_reflection_;
}

void protobuf_AddDesc_noninteracting_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\024noninteracting.proto\022\016noninteracting\"\272"
    "\001\n\nGetEdgePos\022\031\n\021myCurrentBeginPos\030\001 \001(\001"
    "\022\027\n\017myCurrentEndPos\030\002 \001(\001\022\031\n\021myCurrentDu"
    "ration\030\003 \001(\001\022(\n\004time\030\004 \001(\0132\032.noninteract"
    "ing.PBSUMOTime\0223\n\017myLastEntryTime\030\005 \001(\0132"
    "\032.noninteracting.PBSUMOTime\"F\n\006PBEdge\022\026\n"
    "\016fromJunctionId\030\001 \001(\t\022\024\n\014toJunctionId\030\002 "
    "\001(\t\022\016\n\006length\030\003 \001(\001\"\036\n\nPBSUMOTime\022\020\n\010sum"
    "oTime\030\001 \001(\001\"\036\n\nPBSUMOReal\022\020\n\010sumoReal\030\001 "
    "\001(\001\"\247\001\n\027PBMSPersonStage_Walking\022$\n\004edge\030"
    "\001 \001(\0132\026.noninteracting.PBEdge\022-\n\rnextRou"
    "teEdge\030\002 \001(\0132\026.noninteracting.PBEdge\022\021\n\t"
    "departPos\030\003 \001(\001\022\022\n\narrivalPos\030\004 \001(\001\022\020\n\010m"
    "axSpeed\030\005 \001(\001\"\227\001\n\tCMPWlkgTm\022$\n\004prev\030\001 \001("
    "\0132\026.noninteracting.PBEdge\0226\n\005stage\030\002 \001(\013"
    "2\'.noninteracting.PBMSPersonStage_Walkin"
    "g\022,\n\010sumoTime\030\003 \001(\0132\032.noninteracting.PBS"
    "UMOTime\"\211\001\n\014CMPWlkgTmRpl\022,\n\010duration\030\001 \001"
    "(\0132\032.noninteracting.PBSUMOTime\022\027\n\017myLast"
    "EntryTime\030\002 \001(\001\022\031\n\021myCurrentBeginPos\030\003 \001"
    "(\001\022\027\n\017myCurrentEndPos\030\004 \001(\0012\303\002\n\010PBPState"
    "\022O\n\022computeWalkingTime\022\031.noninteracting."
    "CMPWlkgTm\032\034.noninteracting.CMPWlkgTmRpl\""
    "\000\022J\n\016getWaitingTime\022\032.noninteracting.PBS"
    "UMOTime\032\032.noninteracting.PBSUMOTime\"\000\022Q\n"
    "\010getSpeed\022\'.noninteracting.PBMSPersonSta"
    "ge_Walking\032\032.noninteracting.PBSUMOReal\"\000"
    "\022G\n\013getEdgePost\022\032.noninteracting.GetEdge"
    "Pos\032\032.noninteracting.PBSUMOReal\"\000B3\n\032de."
    "dlr.sumo.noninteractingB\023NonInteractingP"
    "rotoP\000b\006proto3", 1214);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "noninteracting.proto", &protobuf_RegisterTypes);
  GetEdgePos::default_instance_ = new GetEdgePos();
  PBEdge::default_instance_ = new PBEdge();
  PBSUMOTime::default_instance_ = new PBSUMOTime();
  PBSUMOReal::default_instance_ = new PBSUMOReal();
  PBMSPersonStage_Walking::default_instance_ = new PBMSPersonStage_Walking();
  CMPWlkgTm::default_instance_ = new CMPWlkgTm();
  CMPWlkgTmRpl::default_instance_ = new CMPWlkgTmRpl();
  GetEdgePos::default_instance_->InitAsDefaultInstance();
  PBEdge::default_instance_->InitAsDefaultInstance();
  PBSUMOTime::default_instance_->InitAsDefaultInstance();
  PBSUMOReal::default_instance_->InitAsDefaultInstance();
  PBMSPersonStage_Walking::default_instance_->InitAsDefaultInstance();
  CMPWlkgTm::default_instance_->InitAsDefaultInstance();
  CMPWlkgTmRpl::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_noninteracting_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_noninteracting_2eproto {
  StaticDescriptorInitializer_noninteracting_2eproto() {
    protobuf_AddDesc_noninteracting_2eproto();
  }
} static_descriptor_initializer_noninteracting_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GetEdgePos::kMyCurrentBeginPosFieldNumber;
const int GetEdgePos::kMyCurrentEndPosFieldNumber;
const int GetEdgePos::kMyCurrentDurationFieldNumber;
const int GetEdgePos::kTimeFieldNumber;
const int GetEdgePos::kMyLastEntryTimeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GetEdgePos::GetEdgePos()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:noninteracting.GetEdgePos)
}

void GetEdgePos::InitAsDefaultInstance() {
  _is_default_instance_ = true;
  time_ = const_cast< ::noninteracting::PBSUMOTime*>(&::noninteracting::PBSUMOTime::default_instance());
  mylastentrytime_ = const_cast< ::noninteracting::PBSUMOTime*>(&::noninteracting::PBSUMOTime::default_instance());
}

GetEdgePos::GetEdgePos(const GetEdgePos& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:noninteracting.GetEdgePos)
}

void GetEdgePos::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  mycurrentbeginpos_ = 0;
  mycurrentendpos_ = 0;
  mycurrentduration_ = 0;
  time_ = NULL;
  mylastentrytime_ = NULL;
}

GetEdgePos::~GetEdgePos() {
  // @@protoc_insertion_point(destructor:noninteracting.GetEdgePos)
  SharedDtor();
}

void GetEdgePos::SharedDtor() {
  if (this != default_instance_) {
    delete time_;
    delete mylastentrytime_;
  }
}

void GetEdgePos::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* GetEdgePos::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return GetEdgePos_descriptor_;
}

const GetEdgePos& GetEdgePos::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_noninteracting_2eproto();
  return *default_instance_;
}

GetEdgePos* GetEdgePos::default_instance_ = NULL;

GetEdgePos* GetEdgePos::New(::google::protobuf::Arena* arena) const {
  GetEdgePos* n = new GetEdgePos;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void GetEdgePos::Clear() {
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<GetEdgePos*>(16)->f)

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(mycurrentbeginpos_, mycurrentduration_);
  if (GetArenaNoVirtual() == NULL && time_ != NULL) delete time_;
  time_ = NULL;
  if (GetArenaNoVirtual() == NULL && mylastentrytime_ != NULL) delete mylastentrytime_;
  mylastentrytime_ = NULL;

#undef ZR_HELPER_
#undef ZR_

}

bool GetEdgePos::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:noninteracting.GetEdgePos)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional double myCurrentBeginPos = 1;
      case 1: {
        if (tag == 9) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &mycurrentbeginpos_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(17)) goto parse_myCurrentEndPos;
        break;
      }

      // optional double myCurrentEndPos = 2;
      case 2: {
        if (tag == 17) {
         parse_myCurrentEndPos:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &mycurrentendpos_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(25)) goto parse_myCurrentDuration;
        break;
      }

      // optional double myCurrentDuration = 3;
      case 3: {
        if (tag == 25) {
         parse_myCurrentDuration:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &mycurrentduration_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_time;
        break;
      }

      // optional .noninteracting.PBSUMOTime time = 4;
      case 4: {
        if (tag == 34) {
         parse_time:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_time()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(42)) goto parse_myLastEntryTime;
        break;
      }

      // optional .noninteracting.PBSUMOTime myLastEntryTime = 5;
      case 5: {
        if (tag == 42) {
         parse_myLastEntryTime:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_mylastentrytime()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:noninteracting.GetEdgePos)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:noninteracting.GetEdgePos)
  return false;
#undef DO_
}

void GetEdgePos::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:noninteracting.GetEdgePos)
  // optional double myCurrentBeginPos = 1;
  if (this->mycurrentbeginpos() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(1, this->mycurrentbeginpos(), output);
  }

  // optional double myCurrentEndPos = 2;
  if (this->mycurrentendpos() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->mycurrentendpos(), output);
  }

  // optional double myCurrentDuration = 3;
  if (this->mycurrentduration() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->mycurrentduration(), output);
  }

  // optional .noninteracting.PBSUMOTime time = 4;
  if (this->has_time()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, *this->time_, output);
  }

  // optional .noninteracting.PBSUMOTime myLastEntryTime = 5;
  if (this->has_mylastentrytime()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5, *this->mylastentrytime_, output);
  }

  // @@protoc_insertion_point(serialize_end:noninteracting.GetEdgePos)
}

::google::protobuf::uint8* GetEdgePos::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:noninteracting.GetEdgePos)
  // optional double myCurrentBeginPos = 1;
  if (this->mycurrentbeginpos() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(1, this->mycurrentbeginpos(), target);
  }

  // optional double myCurrentEndPos = 2;
  if (this->mycurrentendpos() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->mycurrentendpos(), target);
  }

  // optional double myCurrentDuration = 3;
  if (this->mycurrentduration() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(3, this->mycurrentduration(), target);
  }

  // optional .noninteracting.PBSUMOTime time = 4;
  if (this->has_time()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        4, *this->time_, target);
  }

  // optional .noninteracting.PBSUMOTime myLastEntryTime = 5;
  if (this->has_mylastentrytime()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        5, *this->mylastentrytime_, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:noninteracting.GetEdgePos)
  return target;
}

int GetEdgePos::ByteSize() const {
  int total_size = 0;

  // optional double myCurrentBeginPos = 1;
  if (this->mycurrentbeginpos() != 0) {
    total_size += 1 + 8;
  }

  // optional double myCurrentEndPos = 2;
  if (this->mycurrentendpos() != 0) {
    total_size += 1 + 8;
  }

  // optional double myCurrentDuration = 3;
  if (this->mycurrentduration() != 0) {
    total_size += 1 + 8;
  }

  // optional .noninteracting.PBSUMOTime time = 4;
  if (this->has_time()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->time_);
  }

  // optional .noninteracting.PBSUMOTime myLastEntryTime = 5;
  if (this->has_mylastentrytime()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->mylastentrytime_);
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void GetEdgePos::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const GetEdgePos* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const GetEdgePos>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void GetEdgePos::MergeFrom(const GetEdgePos& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from.mycurrentbeginpos() != 0) {
    set_mycurrentbeginpos(from.mycurrentbeginpos());
  }
  if (from.mycurrentendpos() != 0) {
    set_mycurrentendpos(from.mycurrentendpos());
  }
  if (from.mycurrentduration() != 0) {
    set_mycurrentduration(from.mycurrentduration());
  }
  if (from.has_time()) {
    mutable_time()->::noninteracting::PBSUMOTime::MergeFrom(from.time());
  }
  if (from.has_mylastentrytime()) {
    mutable_mylastentrytime()->::noninteracting::PBSUMOTime::MergeFrom(from.mylastentrytime());
  }
}

void GetEdgePos::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GetEdgePos::CopyFrom(const GetEdgePos& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetEdgePos::IsInitialized() const {

  return true;
}

void GetEdgePos::Swap(GetEdgePos* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GetEdgePos::InternalSwap(GetEdgePos* other) {
  std::swap(mycurrentbeginpos_, other->mycurrentbeginpos_);
  std::swap(mycurrentendpos_, other->mycurrentendpos_);
  std::swap(mycurrentduration_, other->mycurrentduration_);
  std::swap(time_, other->time_);
  std::swap(mylastentrytime_, other->mylastentrytime_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata GetEdgePos::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = GetEdgePos_descriptor_;
  metadata.reflection = GetEdgePos_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// GetEdgePos

// optional double myCurrentBeginPos = 1;
void GetEdgePos::clear_mycurrentbeginpos() {
  mycurrentbeginpos_ = 0;
}
 double GetEdgePos::mycurrentbeginpos() const {
  // @@protoc_insertion_point(field_get:noninteracting.GetEdgePos.myCurrentBeginPos)
  return mycurrentbeginpos_;
}
 void GetEdgePos::set_mycurrentbeginpos(double value) {
  
  mycurrentbeginpos_ = value;
  // @@protoc_insertion_point(field_set:noninteracting.GetEdgePos.myCurrentBeginPos)
}

// optional double myCurrentEndPos = 2;
void GetEdgePos::clear_mycurrentendpos() {
  mycurrentendpos_ = 0;
}
 double GetEdgePos::mycurrentendpos() const {
  // @@protoc_insertion_point(field_get:noninteracting.GetEdgePos.myCurrentEndPos)
  return mycurrentendpos_;
}
 void GetEdgePos::set_mycurrentendpos(double value) {
  
  mycurrentendpos_ = value;
  // @@protoc_insertion_point(field_set:noninteracting.GetEdgePos.myCurrentEndPos)
}

// optional double myCurrentDuration = 3;
void GetEdgePos::clear_mycurrentduration() {
  mycurrentduration_ = 0;
}
 double GetEdgePos::mycurrentduration() const {
  // @@protoc_insertion_point(field_get:noninteracting.GetEdgePos.myCurrentDuration)
  return mycurrentduration_;
}
 void GetEdgePos::set_mycurrentduration(double value) {
  
  mycurrentduration_ = value;
  // @@protoc_insertion_point(field_set:noninteracting.GetEdgePos.myCurrentDuration)
}

// optional .noninteracting.PBSUMOTime time = 4;
bool GetEdgePos::has_time() const {
  return !_is_default_instance_ && time_ != NULL;
}
void GetEdgePos::clear_time() {
  if (GetArenaNoVirtual() == NULL && time_ != NULL) delete time_;
  time_ = NULL;
}
const ::noninteracting::PBSUMOTime& GetEdgePos::time() const {
  // @@protoc_insertion_point(field_get:noninteracting.GetEdgePos.time)
  return time_ != NULL ? *time_ : *default_instance_->time_;
}
::noninteracting::PBSUMOTime* GetEdgePos::mutable_time() {
  
  if (time_ == NULL) {
    time_ = new ::noninteracting::PBSUMOTime;
  }
  // @@protoc_insertion_point(field_mutable:noninteracting.GetEdgePos.time)
  return time_;
}
::noninteracting::PBSUMOTime* GetEdgePos::release_time() {
  
  ::noninteracting::PBSUMOTime* temp = time_;
  time_ = NULL;
  return temp;
}
void GetEdgePos::set_allocated_time(::noninteracting::PBSUMOTime* time) {
  delete time_;
  time_ = time;
  if (time) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:noninteracting.GetEdgePos.time)
}

// optional .noninteracting.PBSUMOTime myLastEntryTime = 5;
bool GetEdgePos::has_mylastentrytime() const {
  return !_is_default_instance_ && mylastentrytime_ != NULL;
}
void GetEdgePos::clear_mylastentrytime() {
  if (GetArenaNoVirtual() == NULL && mylastentrytime_ != NULL) delete mylastentrytime_;
  mylastentrytime_ = NULL;
}
const ::noninteracting::PBSUMOTime& GetEdgePos::mylastentrytime() const {
  // @@protoc_insertion_point(field_get:noninteracting.GetEdgePos.myLastEntryTime)
  return mylastentrytime_ != NULL ? *mylastentrytime_ : *default_instance_->mylastentrytime_;
}
::noninteracting::PBSUMOTime* GetEdgePos::mutable_mylastentrytime() {
  
  if (mylastentrytime_ == NULL) {
    mylastentrytime_ = new ::noninteracting::PBSUMOTime;
  }
  // @@protoc_insertion_point(field_mutable:noninteracting.GetEdgePos.myLastEntryTime)
  return mylastentrytime_;
}
::noninteracting::PBSUMOTime* GetEdgePos::release_mylastentrytime() {
  
  ::noninteracting::PBSUMOTime* temp = mylastentrytime_;
  mylastentrytime_ = NULL;
  return temp;
}
void GetEdgePos::set_allocated_mylastentrytime(::noninteracting::PBSUMOTime* mylastentrytime) {
  delete mylastentrytime_;
  mylastentrytime_ = mylastentrytime;
  if (mylastentrytime) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:noninteracting.GetEdgePos.myLastEntryTime)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PBEdge::kFromJunctionIdFieldNumber;
const int PBEdge::kToJunctionIdFieldNumber;
const int PBEdge::kLengthFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PBEdge::PBEdge()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:noninteracting.PBEdge)
}

void PBEdge::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

PBEdge::PBEdge(const PBEdge& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:noninteracting.PBEdge)
}

void PBEdge::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  fromjunctionid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  tojunctionid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  length_ = 0;
}

PBEdge::~PBEdge() {
  // @@protoc_insertion_point(destructor:noninteracting.PBEdge)
  SharedDtor();
}

void PBEdge::SharedDtor() {
  fromjunctionid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  tojunctionid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void PBEdge::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PBEdge::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PBEdge_descriptor_;
}

const PBEdge& PBEdge::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_noninteracting_2eproto();
  return *default_instance_;
}

PBEdge* PBEdge::default_instance_ = NULL;

PBEdge* PBEdge::New(::google::protobuf::Arena* arena) const {
  PBEdge* n = new PBEdge;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void PBEdge::Clear() {
  fromjunctionid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  tojunctionid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  length_ = 0;
}

bool PBEdge::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:noninteracting.PBEdge)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string fromJunctionId = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_fromjunctionid()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->fromjunctionid().data(), this->fromjunctionid().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "noninteracting.PBEdge.fromJunctionId"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_toJunctionId;
        break;
      }

      // optional string toJunctionId = 2;
      case 2: {
        if (tag == 18) {
         parse_toJunctionId:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_tojunctionid()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->tojunctionid().data(), this->tojunctionid().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "noninteracting.PBEdge.toJunctionId"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(25)) goto parse_length;
        break;
      }

      // optional double length = 3;
      case 3: {
        if (tag == 25) {
         parse_length:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &length_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:noninteracting.PBEdge)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:noninteracting.PBEdge)
  return false;
#undef DO_
}

void PBEdge::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:noninteracting.PBEdge)
  // optional string fromJunctionId = 1;
  if (this->fromjunctionid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->fromjunctionid().data(), this->fromjunctionid().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "noninteracting.PBEdge.fromJunctionId");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->fromjunctionid(), output);
  }

  // optional string toJunctionId = 2;
  if (this->tojunctionid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->tojunctionid().data(), this->tojunctionid().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "noninteracting.PBEdge.toJunctionId");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->tojunctionid(), output);
  }

  // optional double length = 3;
  if (this->length() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->length(), output);
  }

  // @@protoc_insertion_point(serialize_end:noninteracting.PBEdge)
}

::google::protobuf::uint8* PBEdge::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:noninteracting.PBEdge)
  // optional string fromJunctionId = 1;
  if (this->fromjunctionid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->fromjunctionid().data(), this->fromjunctionid().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "noninteracting.PBEdge.fromJunctionId");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->fromjunctionid(), target);
  }

  // optional string toJunctionId = 2;
  if (this->tojunctionid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->tojunctionid().data(), this->tojunctionid().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "noninteracting.PBEdge.toJunctionId");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->tojunctionid(), target);
  }

  // optional double length = 3;
  if (this->length() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(3, this->length(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:noninteracting.PBEdge)
  return target;
}

int PBEdge::ByteSize() const {
  int total_size = 0;

  // optional string fromJunctionId = 1;
  if (this->fromjunctionid().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->fromjunctionid());
  }

  // optional string toJunctionId = 2;
  if (this->tojunctionid().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->tojunctionid());
  }

  // optional double length = 3;
  if (this->length() != 0) {
    total_size += 1 + 8;
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PBEdge::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const PBEdge* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const PBEdge>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void PBEdge::MergeFrom(const PBEdge& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from.fromjunctionid().size() > 0) {

    fromjunctionid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.fromjunctionid_);
  }
  if (from.tojunctionid().size() > 0) {

    tojunctionid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.tojunctionid_);
  }
  if (from.length() != 0) {
    set_length(from.length());
  }
}

void PBEdge::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PBEdge::CopyFrom(const PBEdge& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PBEdge::IsInitialized() const {

  return true;
}

void PBEdge::Swap(PBEdge* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PBEdge::InternalSwap(PBEdge* other) {
  fromjunctionid_.Swap(&other->fromjunctionid_);
  tojunctionid_.Swap(&other->tojunctionid_);
  std::swap(length_, other->length_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata PBEdge::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PBEdge_descriptor_;
  metadata.reflection = PBEdge_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// PBEdge

// optional string fromJunctionId = 1;
void PBEdge::clear_fromjunctionid() {
  fromjunctionid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& PBEdge::fromjunctionid() const {
  // @@protoc_insertion_point(field_get:noninteracting.PBEdge.fromJunctionId)
  return fromjunctionid_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void PBEdge::set_fromjunctionid(const ::std::string& value) {
  
  fromjunctionid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:noninteracting.PBEdge.fromJunctionId)
}
 void PBEdge::set_fromjunctionid(const char* value) {
  
  fromjunctionid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:noninteracting.PBEdge.fromJunctionId)
}
 void PBEdge::set_fromjunctionid(const char* value, size_t size) {
  
  fromjunctionid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:noninteracting.PBEdge.fromJunctionId)
}
 ::std::string* PBEdge::mutable_fromjunctionid() {
  
  // @@protoc_insertion_point(field_mutable:noninteracting.PBEdge.fromJunctionId)
  return fromjunctionid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* PBEdge::release_fromjunctionid() {
  
  return fromjunctionid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void PBEdge::set_allocated_fromjunctionid(::std::string* fromjunctionid) {
  if (fromjunctionid != NULL) {
    
  } else {
    
  }
  fromjunctionid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), fromjunctionid);
  // @@protoc_insertion_point(field_set_allocated:noninteracting.PBEdge.fromJunctionId)
}

// optional string toJunctionId = 2;
void PBEdge::clear_tojunctionid() {
  tojunctionid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& PBEdge::tojunctionid() const {
  // @@protoc_insertion_point(field_get:noninteracting.PBEdge.toJunctionId)
  return tojunctionid_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void PBEdge::set_tojunctionid(const ::std::string& value) {
  
  tojunctionid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:noninteracting.PBEdge.toJunctionId)
}
 void PBEdge::set_tojunctionid(const char* value) {
  
  tojunctionid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:noninteracting.PBEdge.toJunctionId)
}
 void PBEdge::set_tojunctionid(const char* value, size_t size) {
  
  tojunctionid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:noninteracting.PBEdge.toJunctionId)
}
 ::std::string* PBEdge::mutable_tojunctionid() {
  
  // @@protoc_insertion_point(field_mutable:noninteracting.PBEdge.toJunctionId)
  return tojunctionid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* PBEdge::release_tojunctionid() {
  
  return tojunctionid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void PBEdge::set_allocated_tojunctionid(::std::string* tojunctionid) {
  if (tojunctionid != NULL) {
    
  } else {
    
  }
  tojunctionid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), tojunctionid);
  // @@protoc_insertion_point(field_set_allocated:noninteracting.PBEdge.toJunctionId)
}

// optional double length = 3;
void PBEdge::clear_length() {
  length_ = 0;
}
 double PBEdge::length() const {
  // @@protoc_insertion_point(field_get:noninteracting.PBEdge.length)
  return length_;
}
 void PBEdge::set_length(double value) {
  
  length_ = value;
  // @@protoc_insertion_point(field_set:noninteracting.PBEdge.length)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PBSUMOTime::kSumoTimeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PBSUMOTime::PBSUMOTime()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:noninteracting.PBSUMOTime)
}

void PBSUMOTime::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

PBSUMOTime::PBSUMOTime(const PBSUMOTime& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:noninteracting.PBSUMOTime)
}

void PBSUMOTime::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  sumotime_ = 0;
}

PBSUMOTime::~PBSUMOTime() {
  // @@protoc_insertion_point(destructor:noninteracting.PBSUMOTime)
  SharedDtor();
}

void PBSUMOTime::SharedDtor() {
  if (this != default_instance_) {
  }
}

void PBSUMOTime::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PBSUMOTime::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PBSUMOTime_descriptor_;
}

const PBSUMOTime& PBSUMOTime::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_noninteracting_2eproto();
  return *default_instance_;
}

PBSUMOTime* PBSUMOTime::default_instance_ = NULL;

PBSUMOTime* PBSUMOTime::New(::google::protobuf::Arena* arena) const {
  PBSUMOTime* n = new PBSUMOTime;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void PBSUMOTime::Clear() {
  sumotime_ = 0;
}

bool PBSUMOTime::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:noninteracting.PBSUMOTime)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional double sumoTime = 1;
      case 1: {
        if (tag == 9) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &sumotime_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:noninteracting.PBSUMOTime)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:noninteracting.PBSUMOTime)
  return false;
#undef DO_
}

void PBSUMOTime::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:noninteracting.PBSUMOTime)
  // optional double sumoTime = 1;
  if (this->sumotime() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(1, this->sumotime(), output);
  }

  // @@protoc_insertion_point(serialize_end:noninteracting.PBSUMOTime)
}

::google::protobuf::uint8* PBSUMOTime::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:noninteracting.PBSUMOTime)
  // optional double sumoTime = 1;
  if (this->sumotime() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(1, this->sumotime(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:noninteracting.PBSUMOTime)
  return target;
}

int PBSUMOTime::ByteSize() const {
  int total_size = 0;

  // optional double sumoTime = 1;
  if (this->sumotime() != 0) {
    total_size += 1 + 8;
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PBSUMOTime::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const PBSUMOTime* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const PBSUMOTime>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void PBSUMOTime::MergeFrom(const PBSUMOTime& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from.sumotime() != 0) {
    set_sumotime(from.sumotime());
  }
}

void PBSUMOTime::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PBSUMOTime::CopyFrom(const PBSUMOTime& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PBSUMOTime::IsInitialized() const {

  return true;
}

void PBSUMOTime::Swap(PBSUMOTime* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PBSUMOTime::InternalSwap(PBSUMOTime* other) {
  std::swap(sumotime_, other->sumotime_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata PBSUMOTime::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PBSUMOTime_descriptor_;
  metadata.reflection = PBSUMOTime_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// PBSUMOTime

// optional double sumoTime = 1;
void PBSUMOTime::clear_sumotime() {
  sumotime_ = 0;
}
 double PBSUMOTime::sumotime() const {
  // @@protoc_insertion_point(field_get:noninteracting.PBSUMOTime.sumoTime)
  return sumotime_;
}
 void PBSUMOTime::set_sumotime(double value) {
  
  sumotime_ = value;
  // @@protoc_insertion_point(field_set:noninteracting.PBSUMOTime.sumoTime)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PBSUMOReal::kSumoRealFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PBSUMOReal::PBSUMOReal()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:noninteracting.PBSUMOReal)
}

void PBSUMOReal::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

PBSUMOReal::PBSUMOReal(const PBSUMOReal& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:noninteracting.PBSUMOReal)
}

void PBSUMOReal::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  sumoreal_ = 0;
}

PBSUMOReal::~PBSUMOReal() {
  // @@protoc_insertion_point(destructor:noninteracting.PBSUMOReal)
  SharedDtor();
}

void PBSUMOReal::SharedDtor() {
  if (this != default_instance_) {
  }
}

void PBSUMOReal::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PBSUMOReal::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PBSUMOReal_descriptor_;
}

const PBSUMOReal& PBSUMOReal::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_noninteracting_2eproto();
  return *default_instance_;
}

PBSUMOReal* PBSUMOReal::default_instance_ = NULL;

PBSUMOReal* PBSUMOReal::New(::google::protobuf::Arena* arena) const {
  PBSUMOReal* n = new PBSUMOReal;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void PBSUMOReal::Clear() {
  sumoreal_ = 0;
}

bool PBSUMOReal::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:noninteracting.PBSUMOReal)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional double sumoReal = 1;
      case 1: {
        if (tag == 9) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &sumoreal_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:noninteracting.PBSUMOReal)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:noninteracting.PBSUMOReal)
  return false;
#undef DO_
}

void PBSUMOReal::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:noninteracting.PBSUMOReal)
  // optional double sumoReal = 1;
  if (this->sumoreal() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(1, this->sumoreal(), output);
  }

  // @@protoc_insertion_point(serialize_end:noninteracting.PBSUMOReal)
}

::google::protobuf::uint8* PBSUMOReal::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:noninteracting.PBSUMOReal)
  // optional double sumoReal = 1;
  if (this->sumoreal() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(1, this->sumoreal(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:noninteracting.PBSUMOReal)
  return target;
}

int PBSUMOReal::ByteSize() const {
  int total_size = 0;

  // optional double sumoReal = 1;
  if (this->sumoreal() != 0) {
    total_size += 1 + 8;
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PBSUMOReal::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const PBSUMOReal* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const PBSUMOReal>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void PBSUMOReal::MergeFrom(const PBSUMOReal& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from.sumoreal() != 0) {
    set_sumoreal(from.sumoreal());
  }
}

void PBSUMOReal::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PBSUMOReal::CopyFrom(const PBSUMOReal& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PBSUMOReal::IsInitialized() const {

  return true;
}

void PBSUMOReal::Swap(PBSUMOReal* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PBSUMOReal::InternalSwap(PBSUMOReal* other) {
  std::swap(sumoreal_, other->sumoreal_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata PBSUMOReal::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PBSUMOReal_descriptor_;
  metadata.reflection = PBSUMOReal_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// PBSUMOReal

// optional double sumoReal = 1;
void PBSUMOReal::clear_sumoreal() {
  sumoreal_ = 0;
}
 double PBSUMOReal::sumoreal() const {
  // @@protoc_insertion_point(field_get:noninteracting.PBSUMOReal.sumoReal)
  return sumoreal_;
}
 void PBSUMOReal::set_sumoreal(double value) {
  
  sumoreal_ = value;
  // @@protoc_insertion_point(field_set:noninteracting.PBSUMOReal.sumoReal)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PBMSPersonStage_Walking::kEdgeFieldNumber;
const int PBMSPersonStage_Walking::kNextRouteEdgeFieldNumber;
const int PBMSPersonStage_Walking::kDepartPosFieldNumber;
const int PBMSPersonStage_Walking::kArrivalPosFieldNumber;
const int PBMSPersonStage_Walking::kMaxSpeedFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PBMSPersonStage_Walking::PBMSPersonStage_Walking()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:noninteracting.PBMSPersonStage_Walking)
}

void PBMSPersonStage_Walking::InitAsDefaultInstance() {
  _is_default_instance_ = true;
  edge_ = const_cast< ::noninteracting::PBEdge*>(&::noninteracting::PBEdge::default_instance());
  nextrouteedge_ = const_cast< ::noninteracting::PBEdge*>(&::noninteracting::PBEdge::default_instance());
}

PBMSPersonStage_Walking::PBMSPersonStage_Walking(const PBMSPersonStage_Walking& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:noninteracting.PBMSPersonStage_Walking)
}

void PBMSPersonStage_Walking::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  edge_ = NULL;
  nextrouteedge_ = NULL;
  departpos_ = 0;
  arrivalpos_ = 0;
  maxspeed_ = 0;
}

PBMSPersonStage_Walking::~PBMSPersonStage_Walking() {
  // @@protoc_insertion_point(destructor:noninteracting.PBMSPersonStage_Walking)
  SharedDtor();
}

void PBMSPersonStage_Walking::SharedDtor() {
  if (this != default_instance_) {
    delete edge_;
    delete nextrouteedge_;
  }
}

void PBMSPersonStage_Walking::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PBMSPersonStage_Walking::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PBMSPersonStage_Walking_descriptor_;
}

const PBMSPersonStage_Walking& PBMSPersonStage_Walking::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_noninteracting_2eproto();
  return *default_instance_;
}

PBMSPersonStage_Walking* PBMSPersonStage_Walking::default_instance_ = NULL;

PBMSPersonStage_Walking* PBMSPersonStage_Walking::New(::google::protobuf::Arena* arena) const {
  PBMSPersonStage_Walking* n = new PBMSPersonStage_Walking;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void PBMSPersonStage_Walking::Clear() {
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<PBMSPersonStage_Walking*>(16)->f)

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(departpos_, maxspeed_);
  if (GetArenaNoVirtual() == NULL && edge_ != NULL) delete edge_;
  edge_ = NULL;
  if (GetArenaNoVirtual() == NULL && nextrouteedge_ != NULL) delete nextrouteedge_;
  nextrouteedge_ = NULL;

#undef ZR_HELPER_
#undef ZR_

}

bool PBMSPersonStage_Walking::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:noninteracting.PBMSPersonStage_Walking)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .noninteracting.PBEdge edge = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_edge()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_nextRouteEdge;
        break;
      }

      // optional .noninteracting.PBEdge nextRouteEdge = 2;
      case 2: {
        if (tag == 18) {
         parse_nextRouteEdge:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_nextrouteedge()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(25)) goto parse_departPos;
        break;
      }

      // optional double departPos = 3;
      case 3: {
        if (tag == 25) {
         parse_departPos:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &departpos_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(33)) goto parse_arrivalPos;
        break;
      }

      // optional double arrivalPos = 4;
      case 4: {
        if (tag == 33) {
         parse_arrivalPos:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &arrivalpos_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(41)) goto parse_maxSpeed;
        break;
      }

      // optional double maxSpeed = 5;
      case 5: {
        if (tag == 41) {
         parse_maxSpeed:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &maxspeed_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:noninteracting.PBMSPersonStage_Walking)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:noninteracting.PBMSPersonStage_Walking)
  return false;
#undef DO_
}

void PBMSPersonStage_Walking::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:noninteracting.PBMSPersonStage_Walking)
  // optional .noninteracting.PBEdge edge = 1;
  if (this->has_edge()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->edge_, output);
  }

  // optional .noninteracting.PBEdge nextRouteEdge = 2;
  if (this->has_nextrouteedge()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *this->nextrouteedge_, output);
  }

  // optional double departPos = 3;
  if (this->departpos() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->departpos(), output);
  }

  // optional double arrivalPos = 4;
  if (this->arrivalpos() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(4, this->arrivalpos(), output);
  }

  // optional double maxSpeed = 5;
  if (this->maxspeed() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(5, this->maxspeed(), output);
  }

  // @@protoc_insertion_point(serialize_end:noninteracting.PBMSPersonStage_Walking)
}

::google::protobuf::uint8* PBMSPersonStage_Walking::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:noninteracting.PBMSPersonStage_Walking)
  // optional .noninteracting.PBEdge edge = 1;
  if (this->has_edge()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, *this->edge_, target);
  }

  // optional .noninteracting.PBEdge nextRouteEdge = 2;
  if (this->has_nextrouteedge()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, *this->nextrouteedge_, target);
  }

  // optional double departPos = 3;
  if (this->departpos() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(3, this->departpos(), target);
  }

  // optional double arrivalPos = 4;
  if (this->arrivalpos() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(4, this->arrivalpos(), target);
  }

  // optional double maxSpeed = 5;
  if (this->maxspeed() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(5, this->maxspeed(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:noninteracting.PBMSPersonStage_Walking)
  return target;
}

int PBMSPersonStage_Walking::ByteSize() const {
  int total_size = 0;

  // optional .noninteracting.PBEdge edge = 1;
  if (this->has_edge()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->edge_);
  }

  // optional .noninteracting.PBEdge nextRouteEdge = 2;
  if (this->has_nextrouteedge()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->nextrouteedge_);
  }

  // optional double departPos = 3;
  if (this->departpos() != 0) {
    total_size += 1 + 8;
  }

  // optional double arrivalPos = 4;
  if (this->arrivalpos() != 0) {
    total_size += 1 + 8;
  }

  // optional double maxSpeed = 5;
  if (this->maxspeed() != 0) {
    total_size += 1 + 8;
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PBMSPersonStage_Walking::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const PBMSPersonStage_Walking* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const PBMSPersonStage_Walking>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void PBMSPersonStage_Walking::MergeFrom(const PBMSPersonStage_Walking& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from.has_edge()) {
    mutable_edge()->::noninteracting::PBEdge::MergeFrom(from.edge());
  }
  if (from.has_nextrouteedge()) {
    mutable_nextrouteedge()->::noninteracting::PBEdge::MergeFrom(from.nextrouteedge());
  }
  if (from.departpos() != 0) {
    set_departpos(from.departpos());
  }
  if (from.arrivalpos() != 0) {
    set_arrivalpos(from.arrivalpos());
  }
  if (from.maxspeed() != 0) {
    set_maxspeed(from.maxspeed());
  }
}

void PBMSPersonStage_Walking::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PBMSPersonStage_Walking::CopyFrom(const PBMSPersonStage_Walking& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PBMSPersonStage_Walking::IsInitialized() const {

  return true;
}

void PBMSPersonStage_Walking::Swap(PBMSPersonStage_Walking* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PBMSPersonStage_Walking::InternalSwap(PBMSPersonStage_Walking* other) {
  std::swap(edge_, other->edge_);
  std::swap(nextrouteedge_, other->nextrouteedge_);
  std::swap(departpos_, other->departpos_);
  std::swap(arrivalpos_, other->arrivalpos_);
  std::swap(maxspeed_, other->maxspeed_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata PBMSPersonStage_Walking::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PBMSPersonStage_Walking_descriptor_;
  metadata.reflection = PBMSPersonStage_Walking_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// PBMSPersonStage_Walking

// optional .noninteracting.PBEdge edge = 1;
bool PBMSPersonStage_Walking::has_edge() const {
  return !_is_default_instance_ && edge_ != NULL;
}
void PBMSPersonStage_Walking::clear_edge() {
  if (GetArenaNoVirtual() == NULL && edge_ != NULL) delete edge_;
  edge_ = NULL;
}
const ::noninteracting::PBEdge& PBMSPersonStage_Walking::edge() const {
  // @@protoc_insertion_point(field_get:noninteracting.PBMSPersonStage_Walking.edge)
  return edge_ != NULL ? *edge_ : *default_instance_->edge_;
}
::noninteracting::PBEdge* PBMSPersonStage_Walking::mutable_edge() {
  
  if (edge_ == NULL) {
    edge_ = new ::noninteracting::PBEdge;
  }
  // @@protoc_insertion_point(field_mutable:noninteracting.PBMSPersonStage_Walking.edge)
  return edge_;
}
::noninteracting::PBEdge* PBMSPersonStage_Walking::release_edge() {
  
  ::noninteracting::PBEdge* temp = edge_;
  edge_ = NULL;
  return temp;
}
void PBMSPersonStage_Walking::set_allocated_edge(::noninteracting::PBEdge* edge) {
  delete edge_;
  edge_ = edge;
  if (edge) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:noninteracting.PBMSPersonStage_Walking.edge)
}

// optional .noninteracting.PBEdge nextRouteEdge = 2;
bool PBMSPersonStage_Walking::has_nextrouteedge() const {
  return !_is_default_instance_ && nextrouteedge_ != NULL;
}
void PBMSPersonStage_Walking::clear_nextrouteedge() {
  if (GetArenaNoVirtual() == NULL && nextrouteedge_ != NULL) delete nextrouteedge_;
  nextrouteedge_ = NULL;
}
const ::noninteracting::PBEdge& PBMSPersonStage_Walking::nextrouteedge() const {
  // @@protoc_insertion_point(field_get:noninteracting.PBMSPersonStage_Walking.nextRouteEdge)
  return nextrouteedge_ != NULL ? *nextrouteedge_ : *default_instance_->nextrouteedge_;
}
::noninteracting::PBEdge* PBMSPersonStage_Walking::mutable_nextrouteedge() {
  
  if (nextrouteedge_ == NULL) {
    nextrouteedge_ = new ::noninteracting::PBEdge;
  }
  // @@protoc_insertion_point(field_mutable:noninteracting.PBMSPersonStage_Walking.nextRouteEdge)
  return nextrouteedge_;
}
::noninteracting::PBEdge* PBMSPersonStage_Walking::release_nextrouteedge() {
  
  ::noninteracting::PBEdge* temp = nextrouteedge_;
  nextrouteedge_ = NULL;
  return temp;
}
void PBMSPersonStage_Walking::set_allocated_nextrouteedge(::noninteracting::PBEdge* nextrouteedge) {
  delete nextrouteedge_;
  nextrouteedge_ = nextrouteedge;
  if (nextrouteedge) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:noninteracting.PBMSPersonStage_Walking.nextRouteEdge)
}

// optional double departPos = 3;
void PBMSPersonStage_Walking::clear_departpos() {
  departpos_ = 0;
}
 double PBMSPersonStage_Walking::departpos() const {
  // @@protoc_insertion_point(field_get:noninteracting.PBMSPersonStage_Walking.departPos)
  return departpos_;
}
 void PBMSPersonStage_Walking::set_departpos(double value) {
  
  departpos_ = value;
  // @@protoc_insertion_point(field_set:noninteracting.PBMSPersonStage_Walking.departPos)
}

// optional double arrivalPos = 4;
void PBMSPersonStage_Walking::clear_arrivalpos() {
  arrivalpos_ = 0;
}
 double PBMSPersonStage_Walking::arrivalpos() const {
  // @@protoc_insertion_point(field_get:noninteracting.PBMSPersonStage_Walking.arrivalPos)
  return arrivalpos_;
}
 void PBMSPersonStage_Walking::set_arrivalpos(double value) {
  
  arrivalpos_ = value;
  // @@protoc_insertion_point(field_set:noninteracting.PBMSPersonStage_Walking.arrivalPos)
}

// optional double maxSpeed = 5;
void PBMSPersonStage_Walking::clear_maxspeed() {
  maxspeed_ = 0;
}
 double PBMSPersonStage_Walking::maxspeed() const {
  // @@protoc_insertion_point(field_get:noninteracting.PBMSPersonStage_Walking.maxSpeed)
  return maxspeed_;
}
 void PBMSPersonStage_Walking::set_maxspeed(double value) {
  
  maxspeed_ = value;
  // @@protoc_insertion_point(field_set:noninteracting.PBMSPersonStage_Walking.maxSpeed)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CMPWlkgTm::kPrevFieldNumber;
const int CMPWlkgTm::kStageFieldNumber;
const int CMPWlkgTm::kSumoTimeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CMPWlkgTm::CMPWlkgTm()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:noninteracting.CMPWlkgTm)
}

void CMPWlkgTm::InitAsDefaultInstance() {
  _is_default_instance_ = true;
  prev_ = const_cast< ::noninteracting::PBEdge*>(&::noninteracting::PBEdge::default_instance());
  stage_ = const_cast< ::noninteracting::PBMSPersonStage_Walking*>(&::noninteracting::PBMSPersonStage_Walking::default_instance());
  sumotime_ = const_cast< ::noninteracting::PBSUMOTime*>(&::noninteracting::PBSUMOTime::default_instance());
}

CMPWlkgTm::CMPWlkgTm(const CMPWlkgTm& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:noninteracting.CMPWlkgTm)
}

void CMPWlkgTm::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  prev_ = NULL;
  stage_ = NULL;
  sumotime_ = NULL;
}

CMPWlkgTm::~CMPWlkgTm() {
  // @@protoc_insertion_point(destructor:noninteracting.CMPWlkgTm)
  SharedDtor();
}

void CMPWlkgTm::SharedDtor() {
  if (this != default_instance_) {
    delete prev_;
    delete stage_;
    delete sumotime_;
  }
}

void CMPWlkgTm::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CMPWlkgTm::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CMPWlkgTm_descriptor_;
}

const CMPWlkgTm& CMPWlkgTm::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_noninteracting_2eproto();
  return *default_instance_;
}

CMPWlkgTm* CMPWlkgTm::default_instance_ = NULL;

CMPWlkgTm* CMPWlkgTm::New(::google::protobuf::Arena* arena) const {
  CMPWlkgTm* n = new CMPWlkgTm;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void CMPWlkgTm::Clear() {
  if (GetArenaNoVirtual() == NULL && prev_ != NULL) delete prev_;
  prev_ = NULL;
  if (GetArenaNoVirtual() == NULL && stage_ != NULL) delete stage_;
  stage_ = NULL;
  if (GetArenaNoVirtual() == NULL && sumotime_ != NULL) delete sumotime_;
  sumotime_ = NULL;
}

bool CMPWlkgTm::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:noninteracting.CMPWlkgTm)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .noninteracting.PBEdge prev = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_prev()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_stage;
        break;
      }

      // optional .noninteracting.PBMSPersonStage_Walking stage = 2;
      case 2: {
        if (tag == 18) {
         parse_stage:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_stage()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_sumoTime;
        break;
      }

      // optional .noninteracting.PBSUMOTime sumoTime = 3;
      case 3: {
        if (tag == 26) {
         parse_sumoTime:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_sumotime()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:noninteracting.CMPWlkgTm)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:noninteracting.CMPWlkgTm)
  return false;
#undef DO_
}

void CMPWlkgTm::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:noninteracting.CMPWlkgTm)
  // optional .noninteracting.PBEdge prev = 1;
  if (this->has_prev()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->prev_, output);
  }

  // optional .noninteracting.PBMSPersonStage_Walking stage = 2;
  if (this->has_stage()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *this->stage_, output);
  }

  // optional .noninteracting.PBSUMOTime sumoTime = 3;
  if (this->has_sumotime()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, *this->sumotime_, output);
  }

  // @@protoc_insertion_point(serialize_end:noninteracting.CMPWlkgTm)
}

::google::protobuf::uint8* CMPWlkgTm::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:noninteracting.CMPWlkgTm)
  // optional .noninteracting.PBEdge prev = 1;
  if (this->has_prev()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, *this->prev_, target);
  }

  // optional .noninteracting.PBMSPersonStage_Walking stage = 2;
  if (this->has_stage()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, *this->stage_, target);
  }

  // optional .noninteracting.PBSUMOTime sumoTime = 3;
  if (this->has_sumotime()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, *this->sumotime_, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:noninteracting.CMPWlkgTm)
  return target;
}

int CMPWlkgTm::ByteSize() const {
  int total_size = 0;

  // optional .noninteracting.PBEdge prev = 1;
  if (this->has_prev()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->prev_);
  }

  // optional .noninteracting.PBMSPersonStage_Walking stage = 2;
  if (this->has_stage()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->stage_);
  }

  // optional .noninteracting.PBSUMOTime sumoTime = 3;
  if (this->has_sumotime()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->sumotime_);
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CMPWlkgTm::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const CMPWlkgTm* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const CMPWlkgTm>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CMPWlkgTm::MergeFrom(const CMPWlkgTm& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from.has_prev()) {
    mutable_prev()->::noninteracting::PBEdge::MergeFrom(from.prev());
  }
  if (from.has_stage()) {
    mutable_stage()->::noninteracting::PBMSPersonStage_Walking::MergeFrom(from.stage());
  }
  if (from.has_sumotime()) {
    mutable_sumotime()->::noninteracting::PBSUMOTime::MergeFrom(from.sumotime());
  }
}

void CMPWlkgTm::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CMPWlkgTm::CopyFrom(const CMPWlkgTm& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CMPWlkgTm::IsInitialized() const {

  return true;
}

void CMPWlkgTm::Swap(CMPWlkgTm* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CMPWlkgTm::InternalSwap(CMPWlkgTm* other) {
  std::swap(prev_, other->prev_);
  std::swap(stage_, other->stage_);
  std::swap(sumotime_, other->sumotime_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata CMPWlkgTm::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CMPWlkgTm_descriptor_;
  metadata.reflection = CMPWlkgTm_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// CMPWlkgTm

// optional .noninteracting.PBEdge prev = 1;
bool CMPWlkgTm::has_prev() const {
  return !_is_default_instance_ && prev_ != NULL;
}
void CMPWlkgTm::clear_prev() {
  if (GetArenaNoVirtual() == NULL && prev_ != NULL) delete prev_;
  prev_ = NULL;
}
const ::noninteracting::PBEdge& CMPWlkgTm::prev() const {
  // @@protoc_insertion_point(field_get:noninteracting.CMPWlkgTm.prev)
  return prev_ != NULL ? *prev_ : *default_instance_->prev_;
}
::noninteracting::PBEdge* CMPWlkgTm::mutable_prev() {
  
  if (prev_ == NULL) {
    prev_ = new ::noninteracting::PBEdge;
  }
  // @@protoc_insertion_point(field_mutable:noninteracting.CMPWlkgTm.prev)
  return prev_;
}
::noninteracting::PBEdge* CMPWlkgTm::release_prev() {
  
  ::noninteracting::PBEdge* temp = prev_;
  prev_ = NULL;
  return temp;
}
void CMPWlkgTm::set_allocated_prev(::noninteracting::PBEdge* prev) {
  delete prev_;
  prev_ = prev;
  if (prev) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:noninteracting.CMPWlkgTm.prev)
}

// optional .noninteracting.PBMSPersonStage_Walking stage = 2;
bool CMPWlkgTm::has_stage() const {
  return !_is_default_instance_ && stage_ != NULL;
}
void CMPWlkgTm::clear_stage() {
  if (GetArenaNoVirtual() == NULL && stage_ != NULL) delete stage_;
  stage_ = NULL;
}
const ::noninteracting::PBMSPersonStage_Walking& CMPWlkgTm::stage() const {
  // @@protoc_insertion_point(field_get:noninteracting.CMPWlkgTm.stage)
  return stage_ != NULL ? *stage_ : *default_instance_->stage_;
}
::noninteracting::PBMSPersonStage_Walking* CMPWlkgTm::mutable_stage() {
  
  if (stage_ == NULL) {
    stage_ = new ::noninteracting::PBMSPersonStage_Walking;
  }
  // @@protoc_insertion_point(field_mutable:noninteracting.CMPWlkgTm.stage)
  return stage_;
}
::noninteracting::PBMSPersonStage_Walking* CMPWlkgTm::release_stage() {
  
  ::noninteracting::PBMSPersonStage_Walking* temp = stage_;
  stage_ = NULL;
  return temp;
}
void CMPWlkgTm::set_allocated_stage(::noninteracting::PBMSPersonStage_Walking* stage) {
  delete stage_;
  stage_ = stage;
  if (stage) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:noninteracting.CMPWlkgTm.stage)
}

// optional .noninteracting.PBSUMOTime sumoTime = 3;
bool CMPWlkgTm::has_sumotime() const {
  return !_is_default_instance_ && sumotime_ != NULL;
}
void CMPWlkgTm::clear_sumotime() {
  if (GetArenaNoVirtual() == NULL && sumotime_ != NULL) delete sumotime_;
  sumotime_ = NULL;
}
const ::noninteracting::PBSUMOTime& CMPWlkgTm::sumotime() const {
  // @@protoc_insertion_point(field_get:noninteracting.CMPWlkgTm.sumoTime)
  return sumotime_ != NULL ? *sumotime_ : *default_instance_->sumotime_;
}
::noninteracting::PBSUMOTime* CMPWlkgTm::mutable_sumotime() {
  
  if (sumotime_ == NULL) {
    sumotime_ = new ::noninteracting::PBSUMOTime;
  }
  // @@protoc_insertion_point(field_mutable:noninteracting.CMPWlkgTm.sumoTime)
  return sumotime_;
}
::noninteracting::PBSUMOTime* CMPWlkgTm::release_sumotime() {
  
  ::noninteracting::PBSUMOTime* temp = sumotime_;
  sumotime_ = NULL;
  return temp;
}
void CMPWlkgTm::set_allocated_sumotime(::noninteracting::PBSUMOTime* sumotime) {
  delete sumotime_;
  sumotime_ = sumotime;
  if (sumotime) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:noninteracting.CMPWlkgTm.sumoTime)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CMPWlkgTmRpl::kDurationFieldNumber;
const int CMPWlkgTmRpl::kMyLastEntryTimeFieldNumber;
const int CMPWlkgTmRpl::kMyCurrentBeginPosFieldNumber;
const int CMPWlkgTmRpl::kMyCurrentEndPosFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CMPWlkgTmRpl::CMPWlkgTmRpl()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:noninteracting.CMPWlkgTmRpl)
}

void CMPWlkgTmRpl::InitAsDefaultInstance() {
  _is_default_instance_ = true;
  duration_ = const_cast< ::noninteracting::PBSUMOTime*>(&::noninteracting::PBSUMOTime::default_instance());
}

CMPWlkgTmRpl::CMPWlkgTmRpl(const CMPWlkgTmRpl& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:noninteracting.CMPWlkgTmRpl)
}

void CMPWlkgTmRpl::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  duration_ = NULL;
  mylastentrytime_ = 0;
  mycurrentbeginpos_ = 0;
  mycurrentendpos_ = 0;
}

CMPWlkgTmRpl::~CMPWlkgTmRpl() {
  // @@protoc_insertion_point(destructor:noninteracting.CMPWlkgTmRpl)
  SharedDtor();
}

void CMPWlkgTmRpl::SharedDtor() {
  if (this != default_instance_) {
    delete duration_;
  }
}

void CMPWlkgTmRpl::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CMPWlkgTmRpl::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CMPWlkgTmRpl_descriptor_;
}

const CMPWlkgTmRpl& CMPWlkgTmRpl::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_noninteracting_2eproto();
  return *default_instance_;
}

CMPWlkgTmRpl* CMPWlkgTmRpl::default_instance_ = NULL;

CMPWlkgTmRpl* CMPWlkgTmRpl::New(::google::protobuf::Arena* arena) const {
  CMPWlkgTmRpl* n = new CMPWlkgTmRpl;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void CMPWlkgTmRpl::Clear() {
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<CMPWlkgTmRpl*>(16)->f)

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(mylastentrytime_, mycurrentendpos_);
  if (GetArenaNoVirtual() == NULL && duration_ != NULL) delete duration_;
  duration_ = NULL;

#undef ZR_HELPER_
#undef ZR_

}

bool CMPWlkgTmRpl::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:noninteracting.CMPWlkgTmRpl)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .noninteracting.PBSUMOTime duration = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_duration()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(17)) goto parse_myLastEntryTime;
        break;
      }

      // optional double myLastEntryTime = 2;
      case 2: {
        if (tag == 17) {
         parse_myLastEntryTime:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &mylastentrytime_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(25)) goto parse_myCurrentBeginPos;
        break;
      }

      // optional double myCurrentBeginPos = 3;
      case 3: {
        if (tag == 25) {
         parse_myCurrentBeginPos:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &mycurrentbeginpos_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(33)) goto parse_myCurrentEndPos;
        break;
      }

      // optional double myCurrentEndPos = 4;
      case 4: {
        if (tag == 33) {
         parse_myCurrentEndPos:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &mycurrentendpos_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:noninteracting.CMPWlkgTmRpl)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:noninteracting.CMPWlkgTmRpl)
  return false;
#undef DO_
}

void CMPWlkgTmRpl::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:noninteracting.CMPWlkgTmRpl)
  // optional .noninteracting.PBSUMOTime duration = 1;
  if (this->has_duration()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->duration_, output);
  }

  // optional double myLastEntryTime = 2;
  if (this->mylastentrytime() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->mylastentrytime(), output);
  }

  // optional double myCurrentBeginPos = 3;
  if (this->mycurrentbeginpos() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->mycurrentbeginpos(), output);
  }

  // optional double myCurrentEndPos = 4;
  if (this->mycurrentendpos() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(4, this->mycurrentendpos(), output);
  }

  // @@protoc_insertion_point(serialize_end:noninteracting.CMPWlkgTmRpl)
}

::google::protobuf::uint8* CMPWlkgTmRpl::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:noninteracting.CMPWlkgTmRpl)
  // optional .noninteracting.PBSUMOTime duration = 1;
  if (this->has_duration()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, *this->duration_, target);
  }

  // optional double myLastEntryTime = 2;
  if (this->mylastentrytime() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->mylastentrytime(), target);
  }

  // optional double myCurrentBeginPos = 3;
  if (this->mycurrentbeginpos() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(3, this->mycurrentbeginpos(), target);
  }

  // optional double myCurrentEndPos = 4;
  if (this->mycurrentendpos() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(4, this->mycurrentendpos(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:noninteracting.CMPWlkgTmRpl)
  return target;
}

int CMPWlkgTmRpl::ByteSize() const {
  int total_size = 0;

  // optional .noninteracting.PBSUMOTime duration = 1;
  if (this->has_duration()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->duration_);
  }

  // optional double myLastEntryTime = 2;
  if (this->mylastentrytime() != 0) {
    total_size += 1 + 8;
  }

  // optional double myCurrentBeginPos = 3;
  if (this->mycurrentbeginpos() != 0) {
    total_size += 1 + 8;
  }

  // optional double myCurrentEndPos = 4;
  if (this->mycurrentendpos() != 0) {
    total_size += 1 + 8;
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CMPWlkgTmRpl::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const CMPWlkgTmRpl* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const CMPWlkgTmRpl>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CMPWlkgTmRpl::MergeFrom(const CMPWlkgTmRpl& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from.has_duration()) {
    mutable_duration()->::noninteracting::PBSUMOTime::MergeFrom(from.duration());
  }
  if (from.mylastentrytime() != 0) {
    set_mylastentrytime(from.mylastentrytime());
  }
  if (from.mycurrentbeginpos() != 0) {
    set_mycurrentbeginpos(from.mycurrentbeginpos());
  }
  if (from.mycurrentendpos() != 0) {
    set_mycurrentendpos(from.mycurrentendpos());
  }
}

void CMPWlkgTmRpl::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CMPWlkgTmRpl::CopyFrom(const CMPWlkgTmRpl& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CMPWlkgTmRpl::IsInitialized() const {

  return true;
}

void CMPWlkgTmRpl::Swap(CMPWlkgTmRpl* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CMPWlkgTmRpl::InternalSwap(CMPWlkgTmRpl* other) {
  std::swap(duration_, other->duration_);
  std::swap(mylastentrytime_, other->mylastentrytime_);
  std::swap(mycurrentbeginpos_, other->mycurrentbeginpos_);
  std::swap(mycurrentendpos_, other->mycurrentendpos_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata CMPWlkgTmRpl::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CMPWlkgTmRpl_descriptor_;
  metadata.reflection = CMPWlkgTmRpl_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// CMPWlkgTmRpl

// optional .noninteracting.PBSUMOTime duration = 1;
bool CMPWlkgTmRpl::has_duration() const {
  return !_is_default_instance_ && duration_ != NULL;
}
void CMPWlkgTmRpl::clear_duration() {
  if (GetArenaNoVirtual() == NULL && duration_ != NULL) delete duration_;
  duration_ = NULL;
}
const ::noninteracting::PBSUMOTime& CMPWlkgTmRpl::duration() const {
  // @@protoc_insertion_point(field_get:noninteracting.CMPWlkgTmRpl.duration)
  return duration_ != NULL ? *duration_ : *default_instance_->duration_;
}
::noninteracting::PBSUMOTime* CMPWlkgTmRpl::mutable_duration() {
  
  if (duration_ == NULL) {
    duration_ = new ::noninteracting::PBSUMOTime;
  }
  // @@protoc_insertion_point(field_mutable:noninteracting.CMPWlkgTmRpl.duration)
  return duration_;
}
::noninteracting::PBSUMOTime* CMPWlkgTmRpl::release_duration() {
  
  ::noninteracting::PBSUMOTime* temp = duration_;
  duration_ = NULL;
  return temp;
}
void CMPWlkgTmRpl::set_allocated_duration(::noninteracting::PBSUMOTime* duration) {
  delete duration_;
  duration_ = duration;
  if (duration) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:noninteracting.CMPWlkgTmRpl.duration)
}

// optional double myLastEntryTime = 2;
void CMPWlkgTmRpl::clear_mylastentrytime() {
  mylastentrytime_ = 0;
}
 double CMPWlkgTmRpl::mylastentrytime() const {
  // @@protoc_insertion_point(field_get:noninteracting.CMPWlkgTmRpl.myLastEntryTime)
  return mylastentrytime_;
}
 void CMPWlkgTmRpl::set_mylastentrytime(double value) {
  
  mylastentrytime_ = value;
  // @@protoc_insertion_point(field_set:noninteracting.CMPWlkgTmRpl.myLastEntryTime)
}

// optional double myCurrentBeginPos = 3;
void CMPWlkgTmRpl::clear_mycurrentbeginpos() {
  mycurrentbeginpos_ = 0;
}
 double CMPWlkgTmRpl::mycurrentbeginpos() const {
  // @@protoc_insertion_point(field_get:noninteracting.CMPWlkgTmRpl.myCurrentBeginPos)
  return mycurrentbeginpos_;
}
 void CMPWlkgTmRpl::set_mycurrentbeginpos(double value) {
  
  mycurrentbeginpos_ = value;
  // @@protoc_insertion_point(field_set:noninteracting.CMPWlkgTmRpl.myCurrentBeginPos)
}

// optional double myCurrentEndPos = 4;
void CMPWlkgTmRpl::clear_mycurrentendpos() {
  mycurrentendpos_ = 0;
}
 double CMPWlkgTmRpl::mycurrentendpos() const {
  // @@protoc_insertion_point(field_get:noninteracting.CMPWlkgTmRpl.myCurrentEndPos)
  return mycurrentendpos_;
}
 void CMPWlkgTmRpl::set_mycurrentendpos(double value) {
  
  mycurrentendpos_ = value;
  // @@protoc_insertion_point(field_set:noninteracting.CMPWlkgTmRpl.myCurrentEndPos)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace noninteracting

// @@protoc_insertion_point(global_scope)
